### ISSUE TITLE
[BUG] bing ai聊天超时

### ISSUE THREAD

**Issue by RickWang000** [lss233/kirara-ai#1069]
### 配置文件：
```
[bing]
# wss_link = "wss://sydney.bing.com/sydney/ChatHub"
# bing_endpoint = "https://edgeservices.bing.com/edgesvc/turing/conversation/create"
show_suggestions = false
show_references = false
show_remaining_count = false
use_drawing = true
[[bing.accounts]]
cookie_content = ‘xxxxx’
```
### 显示回复：

![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/100037219/69ba7f83-d1b0-4797-80f0-65a67b0974af)

### 报错文件：
```
chatgpt-qq-chatgpt-1     | 2023-07-19 06:29:37.331 | ERROR    | utils.retry:wrapper:26 - 处理请求时遇到错误, 将在 12 秒后重试...
chatgpt-qq-chatgpt-1     | 2023-07-19 06:29:59.336 | ERROR    | utils.retry:wrapper:25 - 
chatgpt-qq-chatgpt-1     | Traceback (most recent call last):
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 662, in __await_impl__
chatgpt-qq-chatgpt-1     |     await protocol.handshake(
chatgpt-qq-chatgpt-1     |           │        └ <function WebSocketClientProtocol.handshake at 0x7fc49211a5c0>
chatgpt-qq-chatgpt-1     |           └ <websockets.legacy.client.WebSocketClientProtocol object at 0x7fc4906f9090>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 329, in handshake
chatgpt-qq-chatgpt-1     |     raise InvalidStatusCode(status_code, response_headers)
chatgpt-qq-chatgpt-1     |           │                 │            └ Headers([('X-Cache', 'CONFIG_NOCACHE'), ('nel', '{"report_to":"network-errors","max_age":604800,"success_fraction":0.001,"fai...
chatgpt-qq-chatgpt-1     |           │                 └ 200
chatgpt-qq-chatgpt-1     |           └ <class 'websockets.exceptions.InvalidStatusCode'>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | During handling of the above exception, another exception occurred:
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | Traceback (most recent call last):
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
chatgpt-qq-chatgpt-1     |     return await self.__await_impl__()
chatgpt-qq-chatgpt-1     |                  │    └ <function Connect.__await_impl__ at 0x7fc49211ab60>
chatgpt-qq-chatgpt-1     |                  └ <websockets.legacy.client.Connect object at 0x7fc49149ba50>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 676, in __await_impl__
chatgpt-qq-chatgpt-1     |     await protocol.wait_closed()
chatgpt-qq-chatgpt-1     |           │        └ <function WebSocketCommonProtocol.wait_closed at 0x7fc4921193a0>
chatgpt-qq-chatgpt-1     |           └ <websockets.legacy.client.WebSocketClientProtocol object at 0x7fc4906f9090>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | asyncio.exceptions.CancelledError
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | During handling of the above exception, another exception occurred:
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | Traceback (most recent call last):
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/bot.py", line 59, in <module>
chatgpt-qq-chatgpt-1     |     loop.run_until_complete(asyncio.gather(*bots))
chatgpt-qq-chatgpt-1     |     │    │                  │       │       └ [<Task pending name='Task-5' coro=<start_task() running at /app/platforms/onebot_bot.py:356> wait_for=<_GatheringFuture pendi...
chatgpt-qq-chatgpt-1     |     │    │                  │       └ <function gather at 0x7fc4d0a48900>
chatgpt-qq-chatgpt-1     |     │    │                  └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop.run_until_complete at 0x7fc4d0a4d6c0>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
chatgpt-qq-chatgpt-1     |     self.run_forever()
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop.run_forever at 0x7fc4d0a4d620>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
chatgpt-qq-chatgpt-1     |     self._run_once()
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop._run_once at 0x7fc4d0a4f420>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
chatgpt-qq-chatgpt-1     |     handle._run()
chatgpt-qq-chatgpt-1     |     │      └ <function Handle._run at 0x7fc4d0fac360>
chatgpt-qq-chatgpt-1     |     └ <Handle Task.task_wakeup(<Future cancelled>)>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
chatgpt-qq-chatgpt-1     |     self._context.run(self._callback, *self._args)
chatgpt-qq-chatgpt-1     |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     │    │            │    │           └ <Handle Task.task_wakeup(<Future cancelled>)>
chatgpt-qq-chatgpt-1     |     │    │            │    └ <member '_callback' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     │    │            └ <Handle Task.task_wakeup(<Future cancelled>)>
chatgpt-qq-chatgpt-1     |     │    └ <member '_context' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     └ <Handle Task.task_wakeup(<Future cancelled>)>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | > File "/app/utils/retry.py", line 21, in wrapper
chatgpt-qq-chatgpt-1     |     async for result in func(*args, **kwargs):
chatgpt-qq-chatgpt-1     |                         │     │       └ {'prompt': '你好', 'chain': MessageChain([Plain(text='你好')]), 'name': '王小皮'}
chatgpt-qq-chatgpt-1     |                         │     └ (<conversation.ConversationContext object at 0x7fc491481a50>,)
chatgpt-qq-chatgpt-1     |                         └ <function ConversationContext.ask at 0x7fc49144cd60>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/conversation.py", line 195, in ask
chatgpt-qq-chatgpt-1     |     async for item in self.adapter.ask(prompt):
chatgpt-qq-chatgpt-1     |                       │    │       │   └ '你好'
chatgpt-qq-chatgpt-1     |                       │    │       └ <function BingAdapter.ask at 0x7fc491d519e0>
chatgpt-qq-chatgpt-1     |                       │    └ <adapter.ms.bing.BingAdapter object at 0x7fc4914907d0>
chatgpt-qq-chatgpt-1     |                       └ <conversation.ConversationContext object at 0x7fc491481a50>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/adapter/ms/bing.py", line 121, in ask
chatgpt-qq-chatgpt-1     |     raise e
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/adapter/ms/bing.py", line 63, in ask
chatgpt-qq-chatgpt-1     |     async for final, response in self.bot.ask_stream(prompt=prompt,
chatgpt-qq-chatgpt-1     |                                  │    │   │                 └ '你好'
chatgpt-qq-chatgpt-1     |                                  │    │   └ <function Chatbot.ask_stream at 0x7fc491ca82c0>
chatgpt-qq-chatgpt-1     |                                  │    └ <EdgeGPT.EdgeGPT.Chatbot object at 0x7fc491499d90>
chatgpt-qq-chatgpt-1     |                                  └ <adapter.ms.bing.BingAdapter object at 0x7fc4914907d0>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/EdgeGPT/EdgeGPT.py", line 185, in ask_stream
chatgpt-qq-chatgpt-1     |     async for response in self.chat_hub.ask_stream(
chatgpt-qq-chatgpt-1     |                           │    │        └ <function ChatHub.ask_stream at 0x7fc491c83c40>
chatgpt-qq-chatgpt-1     |                           │    └ <EdgeGPT.chathub.ChatHub object at 0x7fc49147d690>
chatgpt-qq-chatgpt-1     |                           └ <EdgeGPT.EdgeGPT.Chatbot object at 0x7fc491499d90>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/EdgeGPT/chathub.py", line 102, in ask_stream
chatgpt-qq-chatgpt-1     |     async with connect(
chatgpt-qq-chatgpt-1     |                └ <class 'websockets.legacy.client.Connect'>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 637, in __aenter__
chatgpt-qq-chatgpt-1     |     return await self
chatgpt-qq-chatgpt-1     |                  └ <websockets.legacy.client.Connect object at 0x7fc49149ba50>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 654, in __await_impl_timeout__
chatgpt-qq-chatgpt-1     |     async with asyncio_timeout(self.open_timeout):
chatgpt-qq-chatgpt-1     |                │               │    └ 10
chatgpt-qq-chatgpt-1     |                │               └ <websockets.legacy.client.Connect object at 0x7fc49149ba50>
chatgpt-qq-chatgpt-1     |                └ <function timeout at 0x7fc4d0a63ce0>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 98, in __aexit__
chatgpt-qq-chatgpt-1     |     raise TimeoutError
```
之后循环一两次就自动退出这个错误
在此之前出现过error200的错误（issue #1050）但是后来自己好了，过了两天又出现上述错误

**Comment by FQYQC** [comment]
完全一致的问题

**Comment by Nothingness-Void** [comment]
我现在访问bing提示需要用户完成验证

**Comment by Nothingness-Void** [comment]
> 我现在访问bing提示需要用户完成验证

就是这样
出现故障！如果这个问题持续出现，请和我说“reload” 来开启一段新的会话，或者发送 “back” 来回溯到上一条对话，你上一条说的我就当作没看见。
CaptchaChallenge: User needs to solve CAPTCHA to continue.

**Comment by 2521245392** [comment]
我也是bing聊天超时，有没有大佬知道如何解决？

**Comment by 2521245392** [comment]
> > 我现在访问必应提示需要用户完成验证
> 
> 就是这样 出现故障！如果这个问题持续出现，请和我说“reload” 来开启一段新的会话，或者发送 “back” 来回溯到上一条对话，你上一条说的我就当作没看见。验证码挑战：用户需要解决验证码才能继续。

你这个问题登录bing的官网随便发一句话把验证通过了就行了，或者重新填bing的cookie

**Comment by Nothingness-Void** [comment]
> > > 我现在访问必应提示需要用户完成验证
> > 
> > 
> > 就是这样 出现故障！如果这个问题持续出现，请和我说“reload” 来开启一段新的会话，或者发送 “back” 来回溯到上一条对话，你上一条说的我就当作没看见。验证码挑战：用户需要解决验证码才能继续。
> 
> 你这个问题登录bing的官网随便发一句话把验证通过了就行了，或者重新填bing的cookie

官网验证通过了，又碰上了不能输中文的原因，参考了解决方法之后还是不行，只能简单对话不能长对话

**Comment by Nothingness-Void** [comment]
> > > > > 我现在访问必应提示需要用户完成验证
> > > > 
> > > > 
> > > > 就是这样 出现故障！如果这个问题持续出现，请和我说“reload” 来开启一段新的会话，或者发送 “back” 来回溯到上一条对话，你上一条说的我就当作没看见。验证码挑战：用户需要解决验证码才能继续。
> > > 
> > > 
> > > 你这个问题登录bing的官网随便发一句话把验证通过了就行了，或者重新填bing的cookie
> > 
> > 
> > 官网验证通过了，又碰上了不能输中文的原因，参考了解决方法之后还是不行，只能简单对话不能长对话
> 
> 这个问题我是遇见过，我的解决办法是：打开QQ-Chatgpt\python3.11\Lib\site-packages，找到EdgeGPT.py,用记事本编辑搜索所有的 locale=,把=后的东西改成"zh-CN" 保存后记得文件属性勾选只读选项，在重新运行一下程序就解决了 ![屏幕截图 2023-07-27 231343](https://user-images.githubusercontent.com/62867265/256582555-bf7534aa-70f2-4bbb-b9b8-4ec3422a6601.png) 修改前记得备份一下原文件，以免报错可以及时恢复

感谢，我去试试

**Comment by 0smium** [comment]
> > > > > > 我现在访问必应提示需要用户完成验证
> > > > > 
> > > > > 
> > > > > 就是这样 出现故障！如果这个问题持续出现，请和我说“reload” 来开启一段新的会话，或者发送 “back” 来回溯到上一条对话，你上一条说的我就当作没看见。验证码挑战：用户需要解决验证码才能继续。
> > > > 
> > > > 
> > > > 你这个问题登录bing的官网随便发一句话把验证通过了就行了，或者重新填bing的cookie
> > > 
> > > 
> > > 官网验证通过了，又碰上了不能输中文的原因，参考了解决方法之后还是不行，只能简单对话不能长对话
> > 
> > 
> > 这个问题我是遇见过，我的解决办法是：打开QQ-Chatgpt\python3.11\Lib\site-packages，找到EdgeGPT.py,用记事本编辑搜索所有的 locale=,把=后的东西改成"zh-CN" 保存后记得文件属性勾选只读选项，在重新运行一下程序就解决了 ![屏幕截图 2023-07-27 231343](https://user-images.githubusercontent.com/62867265/256582555-bf7534aa-70f2-4bbb-b9b8-4ec3422a6601.png) 修改前记得备份一下原文件，以免报错可以及时恢复
> 
> 改完了，也改成只读了，还是提示这个 `出现故障！如果这个问题持 续出现，请和我说“reload” 来开启一段新的会话，或者发送 “back” 来回溯到上一条对话，你上一条说的我就当作没看见。 InvalidRequest: Culture is not supported. (Parameter 'name') zh_cn is an invalid culture identifier.`

作者之前发过有关中文的解决方案 似乎回退版本就能解决(？ https://github.com/lss233/chatgpt-mirai-qq-bot/commit/5b4b6ab0ab6b5044313e04d2de363e5ae296cf89

**Comment by 0smium** [comment]
> > > > > > > > 我现在访问必应提示需要用户完成验证
> > > > > > > 
> > > > > > > 
> > > > > > > 就是这样 出现故障！如果这个问题持续出现，请和我说“reload” 来开启一段新的会话，或者发送 “back” 来回溯到上一条对话，你上一条说的我就当作没看见。验证码挑战：用户需要解决验证码才能继续。
> > > > > > 
> > > > > > 
> > > > > > 你这个问题登录bing的官网随便发一句话把验证通过了就行了，或者重新填bing的cookie
> > > > > 
> > > > > 
> > > > > 官网验证通过了，又碰上了不能输中文的原因，参考了解决方法之后还是不行，只能简单对话不能长对话
> > > > 
> > > > 
> > > > 这个问题我是遇见过，我的解决办法是：打开QQ-Chatgpt\python3.11\Lib\site-packages，找到EdgeGPT.py,用记事本编辑搜索所有的 locale=,把=后的东西改成"zh-CN" 保存后记得文件属性勾选只读选项，在重新运行一下程序就解决了 ![屏幕截图 2023-07-27 231343](https://user-images.githubusercontent.com/62867265/256582555-bf7534aa-70f2-4bbb-b9b8-4ec3422a6601.png) 修改前记得备份一下原文件，以免报错可以及时恢复
> > > 
> > > 
> > > 改完了，也改成只读了，还是提示这个 `出现故障！如果这个问题持 续出现，请和我说“reload” 来开启一段新的会话，或者发送 “back” 来回溯到上一条对话，你上一条说的我就当作没看见。 InvalidRequest: Culture is not supported. (Parameter 'name') zh_cn is an invalid culture identifier.`
> > 
> > 
> > 作者之前发过有关中文的解决方案 似乎回退版本就能解决(？ [5b4b6ab](https://github.com/lss233/chatgpt-mirai-qq-bot/commit/5b4b6ab0ab6b5044313e04d2de363e5ae296cf89)
> 
> 这个我已经参考过了，不改是完全没法对话，改完能发你好，但是稍微长一点的文本就报错，基本等于没法用

![TK@M{VFE0PHCRUR1{EA~RD0](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/140339951/c6c17639-968f-4d9f-a02a-359c067b30e9)
我这边进行修改之后 长对话就都能跑了

**Comment by 0smium** [comment]
![XHZJ0}WMP0J1D~GVKQ _(`G](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/140339951/1361e934-8641-4c54-8d64-f1bfdbd95f7a)
这个是修改之前的
![QNF2M91LH}L Z4AHHD2HX{G](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/140339951/706c51fa-319e-438c-9d22-fa1a76bd49d2)
这个是改之后的
![~J$G2US%JIO@QNS%A9@0R5R](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/140339951/0a08223c-3bba-4c7f-90d8-5b4ad0434bab)
不清楚我是不是还做过什么修改了 和代理地址有关(? 不清楚了

**Comment by 0smium** [comment]
> > ![XHZJ0}WMP0J1D~GVKQ _(`G](https://user-images.githubusercontent.com/140339951/256617921-1361e934-8641-4c54-8d64-f1bfdbd95f7a.png) 这个是修改之前的 ![QNF2M91LH}L Z4AHHD2HX{G](https://user-images.githubusercontent.com/140339951/256617990-706c51fa-319e-438c-9d22-fa1a76bd49d2.png) 这个是改之后的 ![~J$G2US%JIO@QNS%A9@0R5R](https://user-images.githubusercontent.com/140339951/256618034-0a08223c-3bba-4c7f-90d8-5b4ad0434bab.png) 不清楚我是不是还做过什么修改了 和代理地址有关(? 不清楚了
> 
> ![image](https://user-images.githubusercontent.com/55913486/256618846-c9fd5245-06e2-4ae0-814f-7e801f640a75.png) 我改的ying应该没啥问题，你服务器地区是哪里的 我服务器是美国的

代理是韩国的 bing.py也和你改的一样 那原因大概就不清楚了

**Comment by Arasi2333** [comment]
我也是相同的问题，不知道如何解决

**Comment by thomashooo** [comment]
我现在访问bing提示需要用户完成验证
CaptchaChallenge: User needs to solve CAPTCHA to continue.

添加以下配置之后解决这个问题（v2.5.3，国外服务器）
[bing]
# Bing 的 WS 接入点，通常不需要修改(不加会报错CaptchaChallenge: User needs to solve CAPTCHA to continue.，无法回复)
wss_link = "wss://sydney.bing.com/sydney/ChatHub"
# 会话创建的接入点
bing_endpoint = "https://edgeservices.bing.com/edgesvc/turing/conversation/create"
