### ISSUE TITLE
[BUG] poe似乎连接超时

### ISSUE THREAD

**Issue by 1715819** [lss233/kirara-ai#1070]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
 2023-07-19 13:12:08.507 | INFO     | manager.bot:login_poe:285 - 正在解析第 1 个 poe web 账号
bot-chatgpt-1     | WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (1/10)...
bot-chatgpt-1     | WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (2/10)...
bot-chatgpt-1     | WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (3/10)...
bot-chatgpt-1     | WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (4/10)...
bot-chatgpt-1     | WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (5/10)...
bot-chatgpt-1     | WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (6/10)...
bot-chatgpt-1     | WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (7/10)...
bot-chatgpt-1     | WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (8/10)...
bot-chatgpt-1     | WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (9/10)...
bot-chatgpt-1     | WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (10/10)...
bot-chatgpt-1     | 2023-07-19 13:12:08.636 | ERROR    | manager.bot:login_poe:293 - 解析失败：
bot-chatgpt-1     | 2023-07-19 13:12:08.636 | ERROR    | manager.bot:login_poe:294 - Failed to download https://poe.com too many times.
bot-chatgpt-1     | Traceback (most recent call last):
bot-chatgpt-1     | 
bot-chatgpt-1     |   File "/app/bot.py", line 15, in <module>
bot-chatgpt-1     |     loop.run_until_complete(botManager.login())
bot-chatgpt-1     |     │    │                  │          └ <function BotManager.login at 0x7fd838f30900>
bot-chatgpt-1     |     │    │                  └ <manager.bot.BotManager object at 0x7fd8641cad50>
bot-chatgpt-1     |     │    └ <function BaseEventLoop.run_until_complete at 0x7fd868f594e0>
bot-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
bot-chatgpt-1     | 
bot-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
bot-chatgpt-1     |     self.run_forever()
bot-chatgpt-1     |     │    └ <function BaseEventLoop.run_forever at 0x7fd868f59440>
bot-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
bot-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
bot-chatgpt-1     |     self._run_once()
bot-chatgpt-1     |     │    └ <function BaseEventLoop._run_once at 0x7fd868f5b240>
bot-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
bot-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
bot-chatgpt-1     |     handle._run()
bot-chatgpt-1     |     │      └ <function Handle._run at 0x7fd8694b40e0>
bot-chatgpt-1     |     └ <Handle <TaskStepMethWrapper object at 0x7fd838ee7460>()>
bot-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
bot-chatgpt-1     |     self._context.run(self._callback, *self._args)
bot-chatgpt-1     |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
bot-chatgpt-1     |     │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7fd838ee7460>()>
bot-chatgpt-1     |     │    │            │    └ <member '_callback' of 'Handle' objects>
bot-chatgpt-1     |     │    │            └ <Handle <TaskStepMethWrapper object at 0x7fd838ee7460>()>
bot-chatgpt-1     |     │    └ <member '_context' of 'Handle' objects>
bot-chatgpt-1     |     └ <Handle <TaskStepMethWrapper object at 0x7fd838ee7460>()>
bot-chatgpt-1     | 
bot-chatgpt-1     |   File "/app/manager/bot.py", line 164, in login
bot-chatgpt-1     |     login_func()
bot-chatgpt-1     |     └ <bound method BotManager.login_poe of <manager.bot.BotManager object at 0x7fd8641cad50>>
bot-chatgpt-1     | 
bot-chatgpt-1     | > File "/app/manager/bot.py", line 288, in login_poe
bot-chatgpt-1     |     bot = PoeClient(token=account.p_b, proxy=account.proxy)
bot-chatgpt-1     |           │               │       │          │       └ None
bot-chatgpt-1     |           │               │       │          └ PoeCookieAuth(p_b='xjdRQOgmObv4SQcQHFM3rw%3D%3D', proxy=None)
bot-chatgpt-1     |           │               │       └ 'xjdRQOgmObv4SQcQHFM3rw%3D%3D'
bot-chatgpt-1     |           │               └ PoeCookieAuth(p_b='xjdRQOgmObv4SQcQHFM3rw%3D%3D', proxy=None)
bot-chatgpt-1     |           └ <class 'poe.Client'>
bot-chatgpt-1     | 
bot-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/poe.py", line 150, in __init__
bot-chatgpt-1     |     self.connect_ws()
bot-chatgpt-1     |     │    └ <function Client.connect_ws at 0x7fd867169300>
bot-chatgpt-1     |     └ <poe.Client object at 0x7fd838f82ed0>
bot-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/poe.py", line 411, in connect_ws
bot-chatgpt-1     |     self.setup_connection()
bot-chatgpt-1     |     │    └ <function Client.setup_connection at 0x7fd8671689a0>
bot-chatgpt-1     |     └ <poe.Client object at 0x7fd838f82ed0>
bot-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/poe.py", line 176, in setup_connection
bot-chatgpt-1     |     self.next_data = self.get_next_data(overwrite_vars=True)
bot-chatgpt-1     |     │                │    └ <function Client.get_next_data at 0x7fd867168b80>
bot-chatgpt-1     |     │                └ <poe.Client object at 0x7fd838f82ed0>
bot-chatgpt-1     |     └ <poe.Client object at 0x7fd838f82ed0>
bot-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/poe.py", line 218, in get_next_data
bot-chatgpt-1     |     r = request_with_retries(self.session.get, self.home_url)
bot-chatgpt-1     |         │                    │    │       │    │    └ 'https://poe.com'
bot-chatgpt-1     |         │                    │    │       │    └ <poe.Client object at 0x7fd838f82ed0>
bot-chatgpt-1     |         │                    │    │       └ <function Session.get at 0x7fd8671062a0>
bot-chatgpt-1     |         │                    │    └ <tls_client.sessions.Session object at 0x7fd82b5e3ed0>
bot-chatgpt-1     |         │                    └ <poe.Client object at 0x7fd838f82ed0>
bot-chatgpt-1     |         └ <function request_with_retries at 0x7fd8670d5ee0>
bot-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/poe.py", line 79, in request_with_retries
bot-chatgpt-1     |     raise RuntimeError(f"Failed to download {url} too many times.")
bot-chatgpt-1     | 
bot-chatgpt-1     | RuntimeError: Failed to download https://poe.com too many times.

**运行环境:**  
- 操作系统：
- Docker：yes
- 项目版本：最新

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by KaRuiqin** [comment]
重新拉一下仓库再试试

**Comment by LiangNiang** [comment]
+1

**Comment by 1715819** [comment]
还是超时

**Comment by yanliu110** [comment]
还是超时

**Comment by 200542053** [comment]
linux直接更新poe-api到最新即可修复
win更新poe-api如果失败的话，要把python换为3.10或3.9，然后再更新poe-api

**Comment by zsanjin-p** [comment]
> linux直接更新poe-api到最新即可修复 win更新poe-api如果失败的话，要把python换为3.10或3.9，然后再更新poe-api

请问我这样更新的姿势对吗，但是poe账号还是解析失败，centos7系统：pip3 install --upgrade poe-api
