### ISSUE TITLE
[BUG] 所有 Poe 账号均解析失败

### ISSUE THREAD

**Issue by superhaibao** [lss233/kirara-ai#1102]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况
2023-07-31 22:14:45.745 | ERROR    | manager.bot:login_poe:282 - 解析失败：
2023-07-31 22:14:45.746 | ERROR    | manager.bot:login_poe:283 - failed to do request: Get "https://poe.com": EOF
Traceback (most recent call last):

  File "C:\Users\superhaibao\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\bot.py", line 17, in <module>
    loop.run_until_complete(botManager.login())
    │    │                  │          └ <function BotManager.login at 0x0000016E7E3E8C20>
    │    │                  └ <manager.bot.BotManager object at 0x0000016E7C277B90>
    │    └ <function BaseEventLoop.run_until_complete at 0x0000016E7ADB4360>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x0000016E7E4ED210>()>

  File "C:\Users\superhaibao\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\manager\bot.py", line 109, in
 login
    self.login_poe()
    │    └ <function BotManager.login_poe at 0x0000016E7E3E91C0>
    └ <manager.bot.BotManager object at 0x0000016E7C277B90>

> File "C:\Users\superhaibao\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\manager\bot.py", line 277, in
 login_poe
    bot = PoeClient(token=account.p_b, proxy=account.proxy)
          │               │       │          │       └ 'http://127.0.0.1:7890'
          │               │       │          └ PoeCookieAuth(p_b='iUbhqeAtI6Xi3_cwQ%3D%3D', proxy='http://127.0.0.1:7890')
          │               │       └ 'iUbhqeAt3_cwQ%3D%3D'
          │               └ PoeCookieAuth(p_b='iUbhqeAtIQ%3D%3D', proxy='http://127.0.0.1:7890')
          └ <class 'poe.Client'>

  File "C:\Users\superhaibao\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\python3.11\Lib\site-packages\poe.py", line 123, in __init__
    self.connect_ws()
    │    └ <function Client.connect_ws at 0x0000016E7CCEC040>
    └ <poe.Client object at 0x0000016E7E4140D0>
  File "C:\Users\superhaibao\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\python3.11\Lib\site-packages\poe.py", line 366, in connect_ws
    self.setup_connection()
    │    └ <function Client.setup_connection at 0x0000016E7CCE36A0>
    └ <poe.Client object at 0x0000016E7E4140D0>
  File "C:\Users\superhaibao\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\python3.11\Lib\site-packages\poe.py", line 149, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
    │                │    └ <function Client.get_next_data at 0x0000016E7CCE3880>
    │                └ <poe.Client object at 0x0000016E7E4140D0>
    └ <poe.Client object at 0x0000016E7E4140D0>
  File "C:\Users\superhaibao\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\python3.11\Lib\site-packages\poe.py", line 191, in get_next_data
    r = request_with_retries(self.session.get, self.home_url)
        │                    │    │       │    │    └ 'https://poe.com'
        │                    │    │       │    └ <poe.Client object at 0x0000016E7E4140D0>
        │                    │    │       └ <function Session.get at 0x0000016E7CC85300>
        │                    │    └ <tls_client.sessions.Session object at 0x0000016E7E414350>
        │                    └ <poe.Client object at 0x0000016E7E4140D0>
        └ <function request_with_retries at 0x0000016E7CC62480>
  File "C:\Users\superhaibao\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\python3.11\Lib\site-packages\poe.py", line 45, in request_with_retries
    r = method(*args, **kwargs)
        │       │       └ {}
        │       └ ('https://poe.com',)
        └ <bound method Session.get of <tls_client.sessions.Session object at 0x0000016E7E414350>>
  File "C:\Users\superhaibao\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\python3.11\Lib\site-packages\tls_client\sessions.py", line 422, in get
    return self.execute_request(method="GET", url=url, **kwargs)
           │    │                                 │      └ {}
           │    │                                 └ 'https://poe.com'
           │    └ <function Session.execute_request at 0x0000016E7CC84EA0>
           └ <tls_client.sessions.Session object at 0x0000016E7E414350>
  File "C:\Users\superhaibao\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\python3.11\Lib\site-packages\tls_client\sessions.py", line 405, in execute_request
    raise TLSClientExeption(response_object["body"])
          │                 └ {'id': 'f5cb19fd-3bb5-45d5-8e56-62912a0bbb1c', 'body': 'failed to do request: Get "https://poe.com": EOF', 'cookies': None, '...
          └ <class 'tls_client.exceptions.TLSClientExeption'>

tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://poe.com": EOF
2023-07-31 22:14:45.767 | ERROR    | manager.bot:login_poe:285 - 所有 Poe 账号均解析失败！
2023-07-31 22:14:45.768 | SUCCESS  | manager.bot:login_poe:286 - 成功解析 0/1 个 poe web 账号！
2023-07-31 22:14:45.769 | ERROR    | manager.bot:login:155 - 没有登录成功的账号，程序无法启动！
程序已停止运行。
**运行环境:**  
- 操作系统：Win11
- Docker： ？
- 项目版本：最新

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by weilai-ke-qi** [comment]
同问

**Comment by weilai-ke-qi** [comment]
已发现解决方法#1070
