### ISSUE TITLE
[BUG] 似乎2.5.3版本会出现poe解析失败？

### ISSUE THREAD

**Issue by imRhoAias** [lss233/kirara-ai#1127]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
'NoneType' object has no attribute 'group'

**运行环境:**  
- 操作系统：2012R2
- Docker： ？
- 项目版本：2.5.3

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
2023-08-07 04:35:48.240 | SUCCESS  | config:scan_presets:565 - 检查预设：聊天 <==> presets/issue402.txt [成功]
2023-08-07 04:35:48.240 | SUCCESS  | config:scan_presets:565 - 检查预设：猫娘 <==> presets/role-play/catgirl.txt [成功]
2023-08-07 04:35:48.240 | ERROR    | config:scan_presets:567 - 检查预设：binjiao <==> presets/bingjiao.txt [失败：文件不
存在]
2023-08-07 04:35:48.240 | SUCCESS  | config:scan_presets:565 - 检查预设：玲珑 <==> presets/linglong.txt [成功]
2023-08-07 04:35:48.255 | SUCCESS  | config:scan_presets:578 - 注册预设：bing <==> ./presets\assistant\bing.txt [成功]
2023-08-07 04:35:48.255 | SUCCESS  | config:scan_presets:578 - 注册预设：dan <==> ./presets\assistant\dan.txt [成功]
2023-08-07 04:35:48.255 | SUCCESS  | config:scan_presets:578 - 注册预设：debater <==> ./presets\assistant\debater.txt [
成功]
2023-08-07 04:35:48.255 | SUCCESS  | config:scan_presets:578 - 注册预设：kp <==> ./presets\assistant\kp.txt [成功]
2023-08-07 04:35:48.255 | SUCCESS  | config:scan_presets:578 - 注册预设：lawyer <==> ./presets\assistant\lawyer.txt [成
功]
2023-08-07 04:35:48.255 | SUCCESS  | config:scan_presets:578 - 注册预设：long <==> ./presets\assistant\long.txt [成功]
2023-08-07 04:35:48.255 | SUCCESS  | config:scan_presets:578 - 注册预设：Lss233 <==> ./presets\assistant\Lss233.txt [成
功]
2023-08-07 04:35:48.255 | SUCCESS  | config:scan_presets:578 - 注册预设：novelist <==> ./presets\assistant\novelist.txt
[成功]
2023-08-07 04:35:48.271 | SUCCESS  | config:scan_presets:578 - 注册预设：poet <==> ./presets\assistant\poet.txt [成功]
2023-08-07 04:35:48.271 | SUCCESS  | config:scan_presets:578 - 注册预设：shineisheji <==> ./presets\assistant\shineishe
i.txt [成功]
2023-08-07 04:35:48.271 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl <==> ./presets\role-play\catgirl.txt [
成功]
2023-08-07 04:35:48.271 | SUCCESS  | config:scan_presets:578 - 注册预设：cixiaogui <==> ./presets\role-play\cixiaogui.t
t [成功]
2023-08-07 04:35:48.271 | SUCCESS  | config:scan_presets:578 - 注册预设：crazy <==> ./presets\role-play\crazy.txt [成功

2023-08-07 04:35:48.271 | SUCCESS  | config:scan_presets:578 - 注册预设：debatestick <==> ./presets\role-play\debatesti
k.txt [成功]
2023-08-07 04:35:48.271 | SUCCESS  | config:scan_presets:578 - 注册预设：dingzhen <==> ./presets\role-play\dingzhen.txt
[成功]
2023-08-07 04:35:48.287 | SUCCESS  | config:scan_presets:578 - 注册预设：DJ <==> ./presets\role-play\DJ.txt [成功]
2023-08-07 04:35:48.287 | SUCCESS  | config:scan_presets:578 - 注册预设：ERNIE <==> ./presets\role-play\ERNIE.txt [成功

2023-08-07 04:35:48.287 | SUCCESS  | config:scan_presets:578 - 注册预设：gaoqiqiang <==> ./presets\role-play\gaoqiqiang
txt [成功]
2023-08-07 04:35:48.287 | SUCCESS  | config:scan_presets:578 - 注册预设：hanli <==> ./presets\role-play\hanli.txt [成功

2023-08-07 04:35:48.287 | SUCCESS  | config:scan_presets:578 - 注册预设：huxijin <==> ./presets\role-play\huxijin.txt [
成功]
2023-08-07 04:35:48.302 | SUCCESS  | config:scan_presets:578 - 注册预设：ikun <==> ./presets\role-play\ikun.txt [成功]
2023-08-07 04:35:48.302 | SUCCESS  | config:scan_presets:578 - 注册预设：jiabaili <==> ./presets\role-play\jiabaili.txt
[成功]
2023-08-07 04:35:48.302 | SUCCESS  | config:scan_presets:578 - 注册预设：linruolan <==> ./presets\role-play\linruolan.t
t [成功]
2023-08-07 04:35:48.302 | SUCCESS  | config:scan_presets:578 - 注册预设：MOSS <==> ./presets\role-play\MOSS.txt [成功]
2023-08-07 04:35:48.302 | SUCCESS  | config:scan_presets:578 - 注册预设：PG13succubus <==> ./presets\role-play\PG13succ
bus.txt [成功]
2023-08-07 04:35:48.302 | SUCCESS  | config:scan_presets:578 - 注册预设：powanlang <==> ./presets\role-play\powanlang.t
t [成功]
2023-08-07 04:35:48.318 | SUCCESS  | config:scan_presets:578 - 注册预设：TsundereCatgirl <==> ./presets\role-play\Tsund
reCatgirl.txt [成功]
2023-08-07 04:35:48.318 | SUCCESS  | config:scan_presets:578 - 注册预设：welldone <==> ./presets\role-play\welldone.txt
[成功]
2023-08-07 04:35:48.318 | SUCCESS  | config:scan_presets:578 - 注册预设：yutao <==> ./presets\role-play\yutao.txt [成功

2023-08-07 04:35:48.318 | SUCCESS  | config:scan_presets:578 - 注册预设：zhangweiwei <==> ./presets\role-play\zhangweiw
i.txt [成功]
2023-08-07 04:35:48.333 | ERROR    | config:scan_presets:575 - 注册预设：dan <==> ./presets\utils\dan.txt [失败：关键词
已存在]
2023-08-07 04:35:48.333 | ERROR    | config:scan_presets:575 - 注册预设：catgirl <==> ./presets\catgirl.txt [失败：关键
词已存在]
2023-08-07 04:35:48.333 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl_en <==> ./presets\catgirl_en.txt [成功

2023-08-07 04:35:48.333 | SUCCESS  | config:scan_presets:578 - 注册预设：issue402 <==> ./presets\issue402.txt [成功]
2023-08-07 04:35:48.333 | SUCCESS  | config:scan_presets:578 - 注册预设：linglong <==> ./presets\linglong.txt [成功]
2023-08-07 04:35:48.353 | SUCCESS  | config:scan_presets:578 - 注册预设：预设模板 <==> ./presets\预设模板.txt [成功]
2023-08-07 04:35:48.448 | INFO     | manager.bot:__check_proxy:406 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2023-08-07 04:35:48.588 | SUCCESS  | manager.bot:__check_proxy:414 - [代理测试] 连接成功！
2023-08-07 04:35:48.591 | INFO     | manager.bot:login_poe:285 - 正在解析第 1 个 poe web 账号
2023-08-07 04:35:48.591 | INFO     | manager.bot:__check_proxy:406 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2023-08-07 04:35:48.732 | SUCCESS  | manager.bot:__check_proxy:414 - [代理测试] 连接成功！
2023-08-07 04:35:49.484 | ERROR    | manager.bot:login_poe:293 - 解析失败：
2023-08-07 04:35:49.486 | ERROR    | manager.bot:login_poe:294 - 'NoneType' object has no attribute 'group'
Traceback (most recent call last):

  File "D:\gpt-new\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\bot.py", line 14, in <module>
    loop.run_until_complete(botManager.login())
    │    │                  │          └ <function BotManager.login at 0x0000000EFEEFAEF0>
    │    │                  └ <manager.bot.BotManager object at 0x0000000EFEF11690>
    │    └ <function BaseEventLoop.run_until_complete at 0x0000000EF193B5B0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_un
il_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000000EF31048B0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run
forever
    super().run_forever()

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_fo
ever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000000EF193D090>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_
nce
    handle._run()
    │      └ <function Handle._run at 0x0000000EF18E3D00>
    └ <Handle <TaskStepMethWrapper object at 0x0000000EFF0281F0>()>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x0000000EFF0281F0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x0000000EFF0281F0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x0000000EFF0281F0>()>

  File "D:\gpt-new\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\manager\bot.py", line 164, in log
n
    login_func()
    └ <bound method BotManager.login_poe of <manager.bot.BotManager object at 0x0000000EFEF11690>>

> File "D:\gpt-new\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\manager\bot.py", line 288, in log
n_poe
    bot = PoeClient(token=account.p_b, proxy=account.proxy)
          │               │       │          │       └ 'http://127.0.0.1:7890'
          │               │       │          └ PoeCookieAuth(p_b='TBR3azwId7LkDrGyWKgF7w%3D%3D', proxy='http://127.0.0.
:7890')
          │               │       └ 'TBR3azwId7LkDrGyWKg**w%3D%3D'
          │               └ PoeCookieAuth(p_b='TBR3azwId7LkDrGyWK***w%3D%3D', proxy='http://127.0.0.1:7890')
          └ <class 'poe.Client'>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\poe.py", line 150, in __init__
    self.connect_ws()
    │    └ <function Client.connect_ws at 0x0000000EF7BA9870>
    └ <poe.Client object at 0x0000000EF4387220>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\poe.py", line 411, in connect_
s
    self.setup_connection()
    │    └ <function Client.setup_connection at 0x0000000EF7BA9000>
    └ <poe.Client object at 0x0000000EF4387220>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\poe.py", line 176, in setup_co
nection
    self.next_data = self.get_next_data(overwrite_vars=True)
    │                │    └ <function Client.get_next_data at 0x0000000EF7BA91B0>
    │                └ <poe.Client object at 0x0000000EF4387220>
    └ <poe.Client object at 0x0000000EF4387220>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\poe.py", line 224, in get_next
data
    self.formkey = self.extract_formkey(r.text)
    │              │    │               │ └ '<!DOCTYPE html><html lang="en" class="auto"><head><meta charSet="utf-8"/><
itle>Assistant - Poe</title><meta name="descripti...
    │              │    │               └ <Response [200]>
    │              │    └ <function Client.extract_formkey at 0x0000000EF7BA9120>
    │              └ <poe.Client object at 0x0000000EF4387220>
    └ <poe.Client object at 0x0000000EF4387220>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\poe.py", line 201, in extract_
ormkey
    script_text = re.search(script_regex, html).group(1)
                  │  │      │             └ '<!DOCTYPE html><html lang="en" class="auto"><head><meta charSet="utf-8"/><
itle>Assistant - Poe</title><meta name="descripti...
                  │  │      └ '<script>if\\(.+\\)throw new Error;(.+)</script>'
                  │  └ <function search at 0x0000000EF128C040>
                  └ <module 're' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\lib\\re.p
'>

AttributeError: 'NoneType' object has no attribute 'group'
2023-08-07 04:35:49.605 | ERROR    | manager.bot:login_poe:296 - 所有 Poe 账号均解析失败！
2023-08-07 04:35:49.605 | SUCCESS  | manager.bot:login_poe:297 - 成功解析 0/1 个 poe web 账号！
2023-08-07 04:35:49.605 | INFO     | manager.bot:login_slack:254 - 正在解析第 1 个 Claude (Slack) 账号
2023-08-07 04:35:49.605 | SUCCESS  | manager.bot:login_slack:258 - 解析成功！
2023-08-07 04:35:49.605 | SUCCESS  | manager.bot:login_slack:264 - 成功解析 1/1 个 Claude (Slack) 账号！
2023-08-07 04:35:49.605 | INFO     | manager.bot:login_xinghuo:269 - 正在解析第 1 个 讯飞星火 账号
2023-08-07 04:35:49.605 | SUCCESS  | manager.bot:login_xinghuo:273 - 解析成功！
2023-08-07 04:35:49.621 | SUCCESS  | manager.bot:login_xinghuo:279 - 成功解析 1/1 个 讯飞星火 账号！
2023-08-07 04:35:49.621 | INFO     | manager.bot:handle_openai:107 - 当前的 browserless_endpoint 为：https://chatgpt-pr
xy.lss233.com/api/
2023-08-07 04:35:49.621 | INFO     | manager.bot:handle_openai:123 - 当前的 api_endpoint 为：https://api.nekoai.top/v1
2023-08-07 04:35:49.621 | INFO     | manager.bot:login_openai:340 - 正在登录第 1 个 OpenAI 账号
2023-08-07 04:35:49.621 | INFO     | manager.bot:__login_openai_apikey:527 - 尝试使用 api_key 登录中...
2023-08-07 04:35:49.621 | INFO     | manager.bot:__login_openai_apikey:531 - 当前检查的 API Key 为：sk-F47y9******3euv
2023-08-07 04:35:49.621 | WARNING  | manager.bot:__login_openai_apikey:534 - 在查询 API 额度时遇到问题，请自行确认额度。

2023-08-07 04:35:49.636 | SUCCESS  | manager.bot:login_openai:354 - 登录成功！
2023-08-07 04:35:49.636 | SUCCESS  | manager.bot:login_openai:375 - 成功登录 1/1 个 OpenAI 账号！
2023-08-07 04:35:49.636 | INFO     | manager.bot:login:173 - AI 类型：chatgpt-web - 可用账号： 0 个
2023-08-07 04:35:49.636 | INFO     | manager.bot:login:173 - AI 类型：openai-api - 可用账号： 1 个
2023-08-07 04:35:49.636 | INFO     | manager.bot:login:173 - AI 类型：poe-web - 可用账号： 0 个
2023-08-07 04:35:49.636 | INFO     | manager.bot:login:173 - AI 类型：bing-cookie - 可用账号： 0 个
2023-08-07 04:35:49.636 | INFO     | manager.bot:login:173 - AI 类型：bard-cookie - 可用账号： 0 个
2023-08-07 04:35:49.636 | INFO     | manager.bot:login:173 - AI 类型：yiyan-cookie - 可用账号： 0 个
2023-08-07 04:35:49.636 | INFO     | manager.bot:login:173 - AI 类型：xinghuo-cookie - 可用账号： 1 个
2023-08-07 04:35:49.636 | INFO     | manager.bot:login:173 - AI 类型：chatglm-api - 可用账号： 0 个
2023-08-07 04:35:49.636 | INFO     | manager.bot:login:173 - AI 类型：slack-accesstoken - 可用账号： 1 个
2023-08-07 04:35:49.652 | INFO     | __main__:<module>:25 - 检测到 Onebot 配置，将启动 Onebot 模式……
2023-08-07 04:35:50.244 | INFO     | __main__:<module>:50 - [Edge TTS] 读取 Edge TTS 可用音色列表……
2023-08-07 04:35:55.094 | SUCCESS  | platforms.onebot_bot:startup:349 - 启动完毕，接收消息中……
INFO:quart.serving:Running on http://127.0.0.1:8566 (CTRL + C to quit)
[2023-08-07 04:35:55,100] Running on http://127.0.0.1:8566 (CTRL + C to quit)
2023-08-07 04:35:55.618 | INFO     | __main__:<module>:52 - [Edge TTS] 读取成功！
INFO:quart.serving:127.0.0.1:57641 GET /ws 1.1 101 - 0
[2023-08-07 04:35:57,463] 127.0.0.1:57641 GET /ws 1.1 101 - 0

**其他内容**

**Comment by Haibersut** [comment]
上游依赖问题，poe库尚未更新
https://github.com/lss233/chatgpt-mirai-qq-bot/issues/1118

**Comment by qrzbing** [comment]
看上去一时间是修不好了。。https://github.com/ading2210/poe-api/issues/218

**Comment by thomashooo** [comment]
用不到poe的我直接#掉能跑。
