### ISSUE TITLE
newbing登上去了 但是回复消息就会报错，不知道是哪里设置有问题[Feature] 请在此处填写标题

### ISSUE THREAD

**Issue by alice184516** [lss233/kirara-ai#1148]
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/117461719/82e45465-43f6-49e0-8f4d-e99b596c2af5)

**Comment by alice184516** [comment]
2023-08-12 06:21:36.001 | DEBUG    | platforms.onebot_bot:_:148 - 私聊消息：你好
2023-08-12 06:21:36.001 | ERROR    | universal:handle_message:295 - Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
Traceback (most recent call last):

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\bot.py", line 54, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.t...
    │    │                  │       └ <function gather at 0x000001F83824D3A0>
    │    │                  └ <module 'asyncio' from 'C:\\Users\\Administrator\\Desktop\\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\\python3.11\\python3...
    │    └ <function BaseEventLoop.run_until_complete at 0x000001F838256200>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001F861A2C460>()>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\platforms\onebot_bot.py", line 151, in _
    await handle_message(
          └ <function handle_message at 0x000001F8619ED6C0>

> File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\universal.py", line 261, in handle_message
    conversation_handler.current_conversation = await conversation_handler.create(
    │                    │                            │                    └ <function ConversationHandler.create at 0x000001F8619ECF40>
    │                    │                            └ <conversation.ConversationHandler object at 0x000001F861A0A850>
    │                    └ None
    └ <conversation.ConversationHandler object at 0x000001F861A0A850>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\conversation.py", line 294, in create
    conversation = ConversationContext(_type, self.session_id)
                   │                   │      │    └ 'friend-1845163076'
                   │                   │      └ <conversation.ConversationHandler object at 0x000001F861A0A850>
                   │                   └ 'bing'
                   └ <class 'conversation.ConversationContext'>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\conversation.py", line 96, in __init__
    self.adapter = BingAdapter(self.session_id)
    │              │           │    └ 'friend-1845163076'
    │              │           └ <conversation.ConversationContext object at 0x000001F861A28FD0>
    │              └ <class 'adapter.ms.bing.BingAdapter'>
    └ <conversation.ConversationContext object at 0x000001F861A28FD0>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\adapter\ms\bing.py", line 41, in __init__
    self.cookieData = json.loads(account.cookie_content)
    │    │            │    │     │       └ '[{[{"domain":".bing.com","expirationDate":1723459821.475419,"hostOnly":false,"httpOnly":false,"name":"SnrOvr","path":"/","sa...
    │    │            │    │     └ BingCookiePath(cookie_content='[{[{"domain":".bing.com","expirationDate":1723459821.475419,"hostOnly":false,"httpOnly":false,...
    │    │            │    └ <function loads at 0x000001F838421800>
    │    │            └ <module 'json' from 'C:\\Users\\Administrator\\Desktop\\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\\python3.11\\python311....
    │    └ []
    └ <adapter.ms.bing.BingAdapter object at 0x000001F861A32890>

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 353, in raw_decode

json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
2023-08-12 06:21:36.042 | DEBUG    | platforms.onebot_bot:respond:112 - [OneBot] 尝试发送消息：出现了未知的错误。
Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

**Comment by glaw1984** [comment]
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。
'adaptiveCards'

**Comment by 2521245392** [comment]
解决方法，如果自己搭建了bing聊天服务器，就去bing官网把_U和_KievRPSSecAuth的值重新获取一下
