### ISSUE TITLE
[BUG] OpenAI无法使用账号密码登录

### ISSUE THREAD

**Issue by KawakazeNotFound** [lss233/kirara-ai#1249]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
终端未知错误

**运行环境:**  
- 操作系统：Windows 11 专业工作站版（23H2）
- Docker： ？
- Env:Miniconda3
- 项目版本：2.5.3-维护性更新

**复现步骤**
1.填写[[openai.accounts]]中的账号密码信息
    格式 "
             mode = "browserless"
             # 你的 OpenAI 邮箱
             email = "my（马赛克）@（马赛克）.com"
             # 你的 OpenAI 密码
             password = "sh（马赛克）"

**预期行为**  
正常登陆

**截图**  
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/52972345/0f397e73-1dea-4431-af72-ed4fe212ea19)
![屏幕截图 2023-11-11 000106](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/52972345/884b9e74-59e6-4309-8738-0217673ba6ff)

**其他内容**  
关键报错信息:
2023-11-10 23:52:19.781 | ERROR    | manager.bot:login_openai:371 - 未知错误：
2023-11-10 23:52:19.781 | ERROR    | manager.bot:login_openai:372 - not enough values to unpack (expected 3, got 1)
代理使用:Clash

**Comment by XokoukioX** [comment]
Traceback (most recent call last):

  File "C:\Users\(账户名)\Desktop\Q\Qbot\chatgpt-mirai-qq-bot\bot.py", line 14, in <module>
    loop.run_until_complete(botManager.login())
    │    │                  │          └ <function BotManager.login at 0x00000173EEF6AD40>
    │    │                  └ <manager.bot.BotManager object at 0x00000173EEF8CA30>
    │    └ <function BaseEventLoop.run_until_complete at 0x00000173E53F68C0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\(账户名)\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000173E6C4F7F0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\(账户名)\Miniconda3\envs\chatgpt\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\(账户名)\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000173E53F83A0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\(账户名)\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000173E5387370>
    └ <Handle <TaskStepMethWrapper object at 0x00000173EF21ADD0>()>

  File "C:\Users\(账户名)\Miniconda3\envs\chatgpt\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x00000173EF21ADD0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x00000173EF21ADD0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x00000173EF21ADD0>()>

  File "C:\Users\(账户名)\Desktop\Q\Qbot\chatgpt-mirai-qq-bot\manager\bot.py", line 162, in login
    await login_func()
          └ <bound method BotManager.handle_openai of <manager.bot.BotManager object at 0x00000173EEF8CA30>>

  File "C:\Users\(账户名)\Desktop\Q\Qbot\chatgpt-mirai-qq-bot\manager\bot.py", line 130, in handle_openai
    await self.login_openai()
          │    └ <function BotManager.login_openai at 0x00000173EEF6B2E0>
          └ <manager.bot.BotManager object at 0x00000173EEF8CA30>

> File "C:\Users\(账户名)\Desktop\Q\Qbot\chatgpt-mirai-qq-bot\manager\bot.py", line 346, in login_openai
    bot = await self.__login_V1(account)
                │               └ OpenAIEmailAuth(mode='browserless', proxy='http://127.0.0.1:7890', driver_exec_path=None, browser_exec_path=None, conversatio...
                └ <manager.bot.BotManager object at 0x00000173EEF8CA30>

  File "C:\Users\(账户名)\Desktop\Q\Qbot\chatgpt-mirai-qq-bot\manager\bot.py", line 520, in __login_V1
    if await __V1_check_auth():

  File "C:\Users\(账户名)\Desktop\Q\Qbot\chatgpt-mirai-qq-bot\manager\bot.py", line 451, in __V1_check_auth
    _, payload, _ = access_token.split(".")
                    │            └ <method 'split' of 'str' objects>
                    └ 'None'

ValueError: not enough values to unpack (expected 3, got 1)

**Comment by Nothingness-Void** [comment]
自己搭建接入点才能账号密码登录

**Comment by XokoukioX** [comment]
> 自己搭建接入点才能账号密码登录

请问是哪一个接入点呢?
是api_endpoint还是browserless_endpoint呢?

**Comment by YourFau1t** [comment]
> 账号接入点已经关闭了 用Key访问吧。现在4.0的免费Key都有很多了

请问大佬怎么从哪获得Key orz
