### ISSUE TITLE
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。 原因：Incorrect padding

### ISSUE THREAD

**Issue by 1042171520** [lss233/kirara-ai#1257]
**提交 issue 前，请先确认：**
- [ ] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：？
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
2023-11-22 02:04:28.497 | ERROR    | universal:handle_message:295 - Incorrect padding
Traceback (most recent call last):

  File "D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\bot.py", line 54, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgp...
    │    │                  │       └ <function gather at 0x000002A1DA2E0FE0>
    │    │                  └ <module 'asyncio' from 'D:\\aaaproject\\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\\python3.11\\python311.zip\\asyncio\\__...
    │    └ <function BaseEventLoop.run_until_complete at 0x000002A1DA2F5E40>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\platforms\onebot_bot.py", line 151, in _
    await handle_message(
          └ <function handle_message at 0x000002A1E3AC3D80>

> File "D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\universal.py", line 269, in handle_message
    await action(session_id, message.strip(), conversation_context, respond)
          │      │           │       │        │                     └ <function handle_message.<locals>.respond at 0x000002A1E3AEF420>
          │      │           │       │        └ None
          │      │           │       └ <method 'strip' of 'str' objects>
          │      │           └ '你好啊'
          │      └ 'friend-1042171520'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002A1E3AEF880>

  File "D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002A1E3AEF7E0>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002A1E3AEF420>
          │ │              │           └ '你好啊'
          │ │              └ 'friend-1042171520'
          │ └ <function MiddlewareConcurrentLock.handle_request at 0x000002A1E3AEC680>
          └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x000002A1E3ADC290>

  File "D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\middlewares\concurrentlock.py", line 43, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x000002A1E3AEF420>
          │      │           │       └ None
          │      │           └ '你好啊'
          │      └ 'friend-1042171520'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002A1E3AEF7E0>

  File "D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002A1E3AEF740>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002A1E3AEF420>
          │ │              │           └ '你好啊'
          │ │              └ 'friend-1042171520'
          │ └ <function Middleware.handle_request at 0x000002A1E3AC3920>
          └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x000002A1E3ADC910>

  File "D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\middlewares\middleware.py", line 9, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x000002A1E3AEF420>
          │      │           │       └ None
          │      │           └ '你好啊'
          │      └ 'friend-1042171520'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002A1E3AEF740>

  File "D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002A1E3AEF600>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002A1E3AEF420>
          │ │              │           └ '你好啊'
          │ │              └ 'friend-1042171520'
          │ └ <function MiddlewareRatelimit.handle_request at 0x000002A1E32CE340>
          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x000002A1E3ADC550>

  File "D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\middlewares\ratelimit.py", line 23, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x000002A1E3AEF420>
          │      │           │       └ None
          │      │           └ '你好啊'
          │      └ 'friend-1042171520'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002A1E3AEF600>

  File "D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.request at 0x000002A1E3AEF4C0>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002A1E3AEF420>
          │ │              │           └ '你好啊'
          │ │              └ 'friend-1042171520'
          │ └ <function MiddlewareTimeout.handle_request at 0x000002A1E3AEC7C0>
          └ <middlewares.timeout.MiddlewareTimeout object at 0x000002A1E3ADC890>

  File "D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\middlewares\timeout.py", line 27, in handle_request
    await asyncio.wait_for(coro_task, config.response.max_timeout)
          │       │        │          │      │        └ 600.0
          │       │        │          │      └ Response(mode='mixed', buffer_delay=15, default_ai='xinghuo', error_format='出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” ...
          │       │        │          └ Config(onebot=Onebot(manager_qq=1042171520, reverse_ws_host='0.0.0.0', reverse_ws_port=8566), mirai=None, telegram=None, disc...
          │       │        └ <Task finished name='Task-25' coro=<handle_message.<locals>.request() done, defined at D:\aaaproject\Windows-quickstart-go-cq...
          │       └ <function wait_for at 0x000002A1DA2E0A40>
          └ <module 'asyncio' from 'D:\\aaaproject\\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\\python3.11\\python311.zip\\asyncio\\__...

  File "asyncio\tasks.py", line 479, in wait_for
    for f in todo:

  File "D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\universal.py", line 222, in request
    async for rendered in task:
                          └ <async_generator object retry.<locals>.decorator.<locals>.wrapper at 0x000002A1E3245930>

  File "D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\utils\retry.py", line 21, in wrapper
    async for result in func(*args, **kwargs):
                        │     │       └ {'prompt': '你好啊', 'chain': MessageChain([Plain(text='你好啊')]), 'name': '谁 来剪月光'}
                        │     └ (<conversation.ConversationContext object at 0x000002A1E314AE10>,)
                        └ <function ConversationContext.ask at 0x000002A1E3AC31A0>

  File "D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\conversation.py", line 195, in ask
    async for item in self.adapter.ask(prompt):
                      │    │       │   └ '你好啊'
                      │    │       └ <function XinghuoAdapter.ask at 0x000002A1E394A3E0>
                      │    └ <adapter.xunfei.xinghuo.XinghuoAdapter object at 0x000002A1E314BAD0>
                      └ <conversation.ConversationContext object at 0x000002A1E314AE10>

  File "D:\aaaproject\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\chatgpt\adapter\xunfei\xinghuo.py", line 99, in ask
    decoded_data = base64.b64decode(encoded_data).decode('utf-8')
                   │      │         └ 'estamp":"2023-11-22T02:04:31.164+08:00","status":404,"error":"Not Found","path":"/iflygpt/u/chat_message/chat"}='
                   │      └ <function b64decode at 0x000002A1D84BFEC0>
                   └ <module 'base64' from 'D:\\aaaproject\\Windows-quickstart-go-cqhttp-refs.tags.v2.5.2\\python3.11\\python311.zip\\base64.pyc'>

  File "base64.py", line 88, in b64decode

binascii.Error: Incorrect padding
2023-11-22 02:04:28.552 | DEBUG    | platforms.onebot_bot:respond:112 - [OneBot] 尝试发送消息：出现故障！如果这个问题持 续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
原因：Incorrect padding

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by wjr000** [comment]
楼主解决了嘛，是怎么解决的

**Comment by 1042171520** [comment]
> 楼主解决了嘛，是怎么解决的

没有欸，暂时放弃了这个

**Comment by Enashpinal** [comment]
找到原因了，但是暂时不知道怎么解决
是因为https://xinghuo.xfyun.cn/iflygpt/u/chat_message/chat无法获取数据导致的，可能是网站阻止了
我尝试修改了一下UA为移动端，还是不行
不知道有没有人解决了
