### ISSUE TITLE
最新docker镜像运行报错

### ISSUE THREAD

**Issue by jsxupeng** [lss233/kirara-ai#1264]
stderr: Traceback (most recent call last):
stderr:   File "/app/utils/exithooks.py", line 39, in foo
stderr:     raise hooks.exception
stderr:   File "/app/bot.py", line 26, in <module>
stderr:     from platforms.onebot_bot import start_task
stderr:   File "/app/platforms/onebot_bot.py", line 7, in <module>
stderr:     from aiocqhttp import CQHttp, Event, MessageSegment
stderr:   File "/usr/local/lib/python3.10/site-packages/aiocqhttp/__init__.py", line 19, in <module>
stderr:     from quart import Quart, request, abort, jsonify, websocket, Response
stderr:   File "/usr/local/lib/python3.10/site-packages/quart/__init__.py", line 7, in <module>
stderr:     from .app import Quart
stderr:   File "/usr/local/lib/python3.10/site-packages/quart/app.py", line 46, in <module>
stderr:     from .asgi import ASGIHTTPConnection, ASGILifespan, ASGIWebsocketConnection
stderr:   File "/usr/local/lib/python3.10/site-packages/quart/asgi.py", line 29, in <module>
stderr:     from .debug import traceback_response
stderr:   File "/usr/local/lib/python3.10/site-packages/quart/debug.py", line 8, in <module>
stderr:     from .wrappers import Response
stderr:   File "/usr/local/lib/python3.10/site-packages/quart/wrappers/__init__.py", line 4, in <module>
stderr:     from .request import Body, Request
stderr:   File "/usr/local/lib/python3.10/site-packages/quart/wrappers/request.py", line 23, in <module>
stderr:     from ..formparser import FormDataParser
stderr:   File "/usr/local/lib/python3.10/site-packages/quart/formparser.py", line 23, in <module>
stderr:     from werkzeug.urls import url_decode
stderr: ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/usr/local/lib/python3.10/site-packages/werkzeug/urls.py)

**Comment by clark-2468** [comment]
又是werkzeug

**Comment by clark-2468** [comment]
https://github.com/lss233/chatgpt-mirai-qq-bot/issues/1261

**Comment by clark-2468** [comment]
跟着这个走，记得最后
docker-compose up -d
记得解压压缩包

**Comment by xupeng19881010** [comment]
这个包是不是从老的版本里提取出来的？报错的版本是werkzeug-3.0.1.dist-info

**Comment by rftquella** [comment]
> 跟着这个走，记得最后 docker-compose up -d 记得解压压缩包
照着这个做过了，还是报错ModuleNotFoundError: No module named 'werkzeug.exceptions'
