### ISSUE TITLE
在v3.0.0-alpha2中ChatGPT 网页版 账号设置添加Access Token后点击保存会提示配置文件保存失败

### ISSUE THREAD

**Issue by 2521245392** [lss233/kirara-ai#1280]
报错代码如下
2023-12-26 23:02:46.323 | ERROR    | quart.app:log_exception:1026 - Exception on request POST /backend-api/v1/accounts/chatgpt-web
Traceback (most recent call last):

  File "D:\QQ-bot\chatgpt\bot.py", line 99, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<coroutine object setup_web_service at 0x00000260D8D91A80>]
    │    │                  │       └ <function gather at 0x00000260A148A340>
    │    │                  └ <module 'asyncio' from 'D:\\QQ-bot\\python3.11\\python311.zip\\asyncio\\__init__.pyc'>
    │    └ <function BaseEventLoop.run_until_complete at 0x00000260A14A3060>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "D:\QQ-bot\python3.11\Lib\site-packages\quart\asgi.py", line 90, in handle_request
    response = await self.app.handle_request(request)
                     │    │   │              └ <Request 'http://127.0.0.1:8080/backend-api/v1/accounts/chatgpt-web' [POST]>
                     │    │   └ <function Quart.handle_request at 0x00000260A3732020>
                     │    └ <Quart ''>
                     └ <quart.asgi.ASGIHTTPConnection object at 0x00000260D936ED10>
> File "D:\QQ-bot\python3.11\Lib\site-packages\quart\app.py", line 1489, in handle_request
    return await self.full_dispatch_request(request_context)
                 │    │                     └ <quart.ctx.RequestContext object at 0x00000260D9381E50>
                 │    └ <function Quart.full_dispatch_request at 0x00000260A37320C0>
                 └ <Quart ''>
  File "D:\QQ-bot\python3.11\Lib\site-packages\quart\app.py", line 1514, in full_dispatch_request
    result = await self.handle_user_exception(error)
                   │    └ <function Quart.handle_user_exception at 0x00000260A37311C0>
                   └ <Quart ''>
  File "D:\QQ-bot\python3.11\Lib\site-packages\quart\app.py", line 964, in handle_user_exception
    raise error
          └ AttributeError("'super' object has no attribute '_client'")
  File "D:\QQ-bot\python3.11\Lib\site-packages\quart\app.py", line 1512, in full_dispatch_request
    result = await self.dispatch_request(request_context)
                   │    │                └ <quart.ctx.RequestContext object at 0x00000260D9381E50>
                   │    └ <function Quart.dispatch_request at 0x00000260A3732200>
                   └ <Quart ''>
  File "D:\QQ-bot\python3.11\Lib\site-packages\quart\app.py", line 1557, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
                 │    │            │          │        └ {'key': 'chatgpt-web'}
                 │    │            │          └ <Request 'http://127.0.0.1:8080/backend-api/v1/accounts/chatgpt-web' [POST]>
                 │    │            └ <function route.<locals>.add_new_account at 0x00000260D9320E00>
                 │    └ <function Quart.ensure_async at 0x00000260A3731580>
                 └ <Quart ''>

  File "D:\QQ-bot\chatgpt\framework\platforms\http_service.py", line 82, in wrapper
    return await func(*args, **kwargs)
                 │     │       └ {'key': 'chatgpt-web'}
                 │     └ ()
                 └ <function route.<locals>.add_new_account at 0x00000260D9320D60>

  File "D:\QQ-bot\chatgpt\framework\platforms\http_service.py", line 203, in add_new_account
    account = account_manager.registered_models[key].parse_obj(data)
              │               │                 │              └ {'access_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13Umt...
              │               │                 └ 'chatgpt-web'
              │               └ {'chatgpt-web': <class 'framework.llm.openai.models.OpenAIAccessTokenAuth'>, 'openai-api': <class 'framework.llm.openai.model...
              └ <framework.accounts.manager.AccountManager object at 0x00000260B39C2290>

  File "pydantic\main.py", line 526, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)

  File "D:\QQ-bot\chatgpt\framework\llm\openai\models.py", line 57, in __init__
    super()._client = ChatGPTBrowserChatbot(AsyncChatbot(config={
                      │                     └ <class 'revChatGPT.V1.AsyncChatbot'>
                      └ <class 'framework.chatbot.chatgpt.ChatGPTBrowserChatbot'>

AttributeError: 'super' object has no attribute '_client'
2023-12-26 23:02:46.340 | INFO     | hypercorn.logging:access:88 - 127.0.0.1:60342 POST /backend-api/v1/accounts/chatgpt-web 1.1 500 265 329749
[2023-12-26 23:02:46,340] 127.0.0.1:60342 POST /backend-api/v1/accounts/chatgpt-web 1.1 500 265 329749
[2023-12-26 23:02:46,323] ERROR in app: Exception on request POST /backend-api/v1/accounts/chatgpt-web
Traceback (most recent call last):
  File "D:\QQ-bot\python3.11\Lib\site-packages\quart\app.py", line 1489, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QQ-bot\python3.11\Lib\site-packages\quart\app.py", line 1514, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QQ-bot\python3.11\Lib\site-packages\quart\app.py", line 964, in handle_user_exception
    raise error
  File "D:\QQ-bot\python3.11\Lib\site-packages\quart\app.py", line 1512, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QQ-bot\python3.11\Lib\site-packages\quart\app.py", line 1557, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QQ-bot\chatgpt\framework\platforms\http_service.py", line 82, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QQ-bot\chatgpt\framework\platforms\http_service.py", line 203, in add_new_account
    account = account_manager.registered_models[key].parse_obj(data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 526, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "D:\QQ-bot\chatgpt\framework\llm\openai\models.py", line 57, in __init__
    super()._client = ChatGPTBrowserChatbot(AsyncChatbot(config={
    ^^^^^^^^^^^^^^^
AttributeError: 'super' object has no attribute '_client'

**Comment by zhi-feng2008** [comment]
同样
