### ISSUE TITLE
[BUG] 讯飞星火不能正常回复，提示list index out of range

### ISSUE THREAD

**Issue by dongbeiboy** [lss233/kirara-ai#1297]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：Windows Server 2022 with Container 数据中心版 64位中文版 阿里云
- Docker：no
- 项目版本：2.5.3

**复现步骤**  
描述你是如何触发这个 BUG 的
就是正常配置，然后等待讯飞星火回消息

**预期行为**  
描述你认为正常情况下应该看见的情况

给个回复
**截图**  
相关日志、聊天记录的截图，没有可跳过
2024-01-26 00:03:39.262 | DEBUG    | platforms.http_service:process_request:115 - Bot request 1706198617791 done.
2024-01-26 00:07:23.144 | INFO     | platforms.http_service:construct_bot_request:174 - Get message from 手动打码[手动打码2]:
你好
2024-01-26 00:07:23.160 | DEBUG    | platforms.http_service:process_request:101 - Start to process bot request 1706198843160.
2024-01-26 00:07:23.163 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
2024-01-26 00:07:23.163 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
[2024-01-26 00:07:23,163] 36.132.216.170:6544 POST /v2/chat 1.1 200 13 19454
INFO:quart.serving:36.132.216.170:6544 POST /v2/chat 1.1 200 13 19454
INFO:quart.serving:36.132.216.170:6544 POST /v2/chat 1.1 - - 19454
[2024-01-26 00:07:23,163] 36.132.216.170:6544 POST /v2/chat 1.1 - - 19454
2024-01-26 00:07:23.163 | DEBUG    | middlewares.timeout:create_timeout_task:61 - [Timeout] 开始计时……
2024-01-26 00:07:23.274 | DEBUG    | platforms.http_service:v2_chat_response:151 - Bot request 1706198843160 response ->
{"result": "SUCCESS", "message": [], "voice": [], "image": []}
INFO:quart.serving:36.132.216.170:6544 GET /v2/chat/response 1.1 200 62 2071
[2024-01-26 00:07:23,275] 36.132.216.170:6544 GET /v2/chat/response 1.1 200 62 2071
INFO:quart.serving:36.132.216.170:6544 GET /v2/chat/response 1.1 - - 3116
[2024-01-26 00:07:23,277] 36.132.216.170:6544 GET /v2/chat/response 1.1 - - 3116
2024-01-26 00:07:24.549 | DEBUG    | adapter.xunfei.xinghuo:ask:107 - [Xinghuo] 177839656 - 你好，我在这里。你需要我回答什么问题或提供什么帮助吗？
2024-01-26 00:07:24.549 | DEBUG    | middlewares.timeout:handle_respond:52 - [Timeout] 取消计时……
2024-01-26 00:07:24.549 | INFO     | platforms.http_service:response:86 - Got response msg -> <class 'graia.ariadne.message.chain.MessageChain'> -> 你好，我在这里。你需要我回答什么问题或提供什么帮助吗？
2024-01-26 00:07:24.556 | DEBUG    | middlewares.timeout:create_timeout_task:61 - [Timeout] 开始计时……
2024-01-26 00:07:24.556 | ERROR    | middlewares.timeout:handle_request:36 - 发生错误: list index out of range
2024-01-26 00:07:24.556 | ERROR    | universal:handle_message:297 - list index out of range
Traceback (most recent call last):

  File "C:\bot\chatgpt-mirai-qq-bot\bot.py", line 58, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at C:\bot\chatgpt-mirai-qq-bot\platforms\http_service.py:185> wait_fo...
    │    │                  │       └ <function gather at 0x000002D3A1B40790>
    │    │                  └ <module 'asyncio' from 'C:\\Users\\Administrator\\Miniconda3\\envs\\chatgpt\\lib\\asyncio\\__init__.py'>
    │    └ <function BaseEventLoop.run_until_complete at 0x000002D3A1B4D480>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000002D3A3782170>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000002D3A1B4EEF0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002D3A1AEA050>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\bot\chatgpt-mirai-qq-bot\platforms\http_service.py", line 106, in process_request
    await handle_message(
          └ <function handle_message at 0x000002D3CD2C9000>

> File "C:\bot\chatgpt-mirai-qq-bot\universal.py", line 271, in handle_message
    await action(session_id, message.strip(), conversation_context, respond)
          │      │           │       │        │                     └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │      │           │       │        └ <conversation.ConversationContext object at 0x000002D3CD3C6E90>
          │      │           │       └ <method 'strip' of 'str' objects>
          │      │           └ '你好'
          │      └ '手动打码'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002D3CD4BC280>

  File "C:\bot\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002D3CD4BC1F0>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │ │              │           └ '你好'
          │ │              └ '手动打码'
          │ └ <function MiddlewareConcurrentLock.handle_request at 0x000002D3CD2C9B40>
          └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x000002D3CD2AB7C0>

  File "C:\bot\chatgpt-mirai-qq-bot\middlewares\concurrentlock.py", line 43, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ '手动打码'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002D3CD4BC1F0>

  File "C:\bot\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002D3CD4BC160>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │ │              │           └ '你好'
          │ │              └ '手动打码'
          │ └ <function Middleware.handle_request at 0x000002D3CD2C9120>
          └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x000002D3CBF4FFD0>

  File "C:\bot\chatgpt-mirai-qq-bot\middlewares\middleware.py", line 9, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ '手动打码'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002D3CD4BC160>

  File "C:\bot\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002D3CD4BC0D0>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │ │              │           └ '你好'
          │ │              └ '手动打码'
          │ └ <function MiddlewareRatelimit.handle_request at 0x000002D3CD2C9CF0>
          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x000002D3CBF4FFA0>

  File "C:\bot\chatgpt-mirai-qq-bot\middlewares\ratelimit.py", line 23, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ '手动打码'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002D3CD4BC0D0>

  File "C:\bot\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.request at 0x000002D3CD4BC040>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │ │              │           └ '你好'
          │ │              └ '手动打码'
          │ └ <function MiddlewareTimeout.handle_request at 0x000002D3CD2C9EA0>
          └ <middlewares.timeout.MiddlewareTimeout object at 0x000002D3CBF4FF70>

  File "C:\bot\chatgpt-mirai-qq-bot\middlewares\timeout.py", line 40, in handle_request
    raise e

  File "C:\bot\chatgpt-mirai-qq-bot\middlewares\timeout.py", line 27, in handle_request
    await asyncio.wait_for(coro_task, config.response.max_timeout)
          │       │        │          │      │        └ 600.0
          │       │        │          │      └ Response(mode='mixed', buffer_delay=0.0, default_ai='xinghuo', error_format='出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话”...
          │       │        │          └ Config(onebot=None, mirai=None, telegram=None, discord=None, http=HttpService(host='172.16.189.148', port=52131, debug=False)...
          │       │        └ <Task finished name='Task-111' coro=<handle_message.<locals>.request() done, defined at C:\bot\chatgpt-mirai-qq-bot\universal...
          │       └ <function wait_for at 0x000002D3A1B40280>
          └ <module 'asyncio' from 'C:\\Users\\Administrator\\Miniconda3\\envs\\chatgpt\\lib\\asyncio\\__init__.py'>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
           │   └ <method 'result' of '_asyncio.Task' objects>
           └ <Task finished name='Task-111' coro=<handle_message.<locals>.request() done, defined at C:\bot\chatgpt-mirai-qq-bot\universal...

  File "C:\bot\chatgpt-mirai-qq-bot\universal.py", line 236, in request
    await m.handle_respond_completed(session_id, prompt, respond)
          │ │                        │           │       └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │ │                        │           └ '你好'
          │ │                        └ '手动打码'
          │ └ <function MiddlewareRatelimit.handle_respond_completed at 0x000002D3CD2C9D80>
          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x000002D3CBF4FFA0>

  File "C:\bot\chatgpt-mirai-qq-bot\middlewares\ratelimit.py", line 27, in handle_respond_completed
    msg_id = session_id.split('-', 1)[1]
             │          └ <method 'split' of 'str' objects>
             └ '手动打码'

IndexError: list index out of range
2024-01-26 00:07:24.556 | INFO     | platforms.http_service:response:86 - Got response msg -> <class 'str'> -> 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说 的我就当作没看见。
list index out of range
2024-01-26 00:07:24.556 | DEBUG    | platforms.http_service:process_request:115 - Bot request 1706198843160 done.

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by dongbeiboy** [comment]
> **提交 issue 前，请先确认：**
> 
> * [√]  我已看过 **FAQ**，此问题不在列表中
> * [√]  我已看过其他 issue，他们不能解决我的问题
> * [  ]  我认为这不是 Mirai 或者 OpenAI 的 BUG
> 
> **表现** 描述 BUG 的表现情况
> 不能正常回复消息
> **运行环境:**
> 
> * 操作系统：Windows Server 2022 with Container 数据中心版 64位中文版 阿里云的
> * Docker：no
> * 项目版本：2.5.3
> 
> **复现步骤** 描述你是如何触发这个 BUG 的 
就是正常配置，然后等待讯飞星火回消息
> 
> **预期行为** 描述你认为正常情况下应该看见的情况
> 回复消息

> 
 **截图** 相关日志、聊天记录的截图，没有可跳过
 
> 
> **其他内容** 此处填写其他内容，没有可跳过

2024-01-26 00:03:39.262 | DEBUG    | platforms.http_service:process_request:115 - Bot request 1706198617791 done.
2024-01-26 00:07:23.144 | INFO     | platforms.http_service:construct_bot_request:174 - Get message from 手动打码[手动打码2]:
你好
2024-01-26 00:07:23.160 | DEBUG    | platforms.http_service:process_request:101 - Start to process bot request 1706198843160.
2024-01-26 00:07:23.163 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
2024-01-26 00:07:23.163 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
[2024-01-26 00:07:23,163] 36.132.216.170:6544 POST /v2/chat 1.1 200 13 19454
INFO:quart.serving:36.132.216.170:6544 POST /v2/chat 1.1 200 13 19454
INFO:quart.serving:36.132.216.170:6544 POST /v2/chat 1.1 - - 19454
[2024-01-26 00:07:23,163] 36.132.216.170:6544 POST /v2/chat 1.1 - - 19454
2024-01-26 00:07:23.163 | DEBUG    | middlewares.timeout:create_timeout_task:61 - [Timeout] 开始计时……
2024-01-26 00:07:23.274 | DEBUG    | platforms.http_service:v2_chat_response:151 - Bot request 1706198843160 response ->
{"result": "SUCCESS", "message": [], "voice": [], "image": []}
INFO:quart.serving:36.132.216.170:6544 GET /v2/chat/response 1.1 200 62 2071
[2024-01-26 00:07:23,275] 36.132.216.170:6544 GET /v2/chat/response 1.1 200 62 2071
INFO:quart.serving:36.132.216.170:6544 GET /v2/chat/response 1.1 - - 3116
[2024-01-26 00:07:23,277] 36.132.216.170:6544 GET /v2/chat/response 1.1 - - 3116
2024-01-26 00:07:24.549 | DEBUG    | adapter.xunfei.xinghuo:ask:107 - [Xinghuo] 177839656 - 你好，我在这里。你需要我回答什么问题或提供什么帮助吗？
2024-01-26 00:07:24.549 | DEBUG    | middlewares.timeout:handle_respond:52 - [Timeout] 取消计时……
2024-01-26 00:07:24.549 | INFO     | platforms.http_service:response:86 - Got response msg -> <class 'graia.ariadne.message.chain.MessageChain'> -> 你好，我在这里。你需要我回答什么问题或提供什么帮助吗？
2024-01-26 00:07:24.556 | DEBUG    | middlewares.timeout:create_timeout_task:61 - [Timeout] 开始计时……
2024-01-26 00:07:24.556 | ERROR    | middlewares.timeout:handle_request:36 - 发生错误: list index out of range
2024-01-26 00:07:24.556 | ERROR    | universal:handle_message:297 - list index out of range
Traceback (most recent call last):

  File "C:\bot\chatgpt-mirai-qq-bot\bot.py", line 58, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at C:\bot\chatgpt-mirai-qq-bot\platforms\http_service.py:185> wait_fo...
    │    │                  │       └ <function gather at 0x000002D3A1B40790>
    │    │                  └ <module 'asyncio' from 'C:\\Users\\Administrator\\Miniconda3\\envs\\chatgpt\\lib\\asyncio\\__init__.py'>
    │    └ <function BaseEventLoop.run_until_complete at 0x000002D3A1B4D480>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000002D3A3782170>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000002D3A1B4EEF0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002D3A1AEA050>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\bot\chatgpt-mirai-qq-bot\platforms\http_service.py", line 106, in process_request
    await handle_message(
          └ <function handle_message at 0x000002D3CD2C9000>

> File "C:\bot\chatgpt-mirai-qq-bot\universal.py", line 271, in handle_message
    await action(session_id, message.strip(), conversation_context, respond)
          │      │           │       │        │                     └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │      │           │       │        └ <conversation.ConversationContext object at 0x000002D3CD3C6E90>
          │      │           │       └ <method 'strip' of 'str' objects>
          │      │           └ '你好'
          │      └ '手动打码'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002D3CD4BC280>

  File "C:\bot\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002D3CD4BC1F0>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │ │              │           └ '你好'
          │ │              └ '手动打码'
          │ └ <function MiddlewareConcurrentLock.handle_request at 0x000002D3CD2C9B40>
          └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x000002D3CD2AB7C0>

  File "C:\bot\chatgpt-mirai-qq-bot\middlewares\concurrentlock.py", line 43, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ '手动打码'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002D3CD4BC1F0>

  File "C:\bot\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002D3CD4BC160>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │ │              │           └ '你好'
          │ │              └ '手动打码'
          │ └ <function Middleware.handle_request at 0x000002D3CD2C9120>
          └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x000002D3CBF4FFD0>

  File "C:\bot\chatgpt-mirai-qq-bot\middlewares\middleware.py", line 9, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ '手动打码'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002D3CD4BC160>

  File "C:\bot\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002D3CD4BC0D0>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │ │              │           └ '你好'
          │ │              └ '手动打码'
          │ └ <function MiddlewareRatelimit.handle_request at 0x000002D3CD2C9CF0>
          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x000002D3CBF4FFA0>

  File "C:\bot\chatgpt-mirai-qq-bot\middlewares\ratelimit.py", line 23, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ '手动打码'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002D3CD4BC0D0>

  File "C:\bot\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.request at 0x000002D3CD4BC040>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │ │              │           └ '你好'
          │ │              └ '手动打码'
          │ └ <function MiddlewareTimeout.handle_request at 0x000002D3CD2C9EA0>
          └ <middlewares.timeout.MiddlewareTimeout object at 0x000002D3CBF4FF70>

  File "C:\bot\chatgpt-mirai-qq-bot\middlewares\timeout.py", line 40, in handle_request
    raise e

  File "C:\bot\chatgpt-mirai-qq-bot\middlewares\timeout.py", line 27, in handle_request
    await asyncio.wait_for(coro_task, config.response.max_timeout)
          │       │        │          │      │        └ 600.0
          │       │        │          │      └ Response(mode='mixed', buffer_delay=0.0, default_ai='xinghuo', error_format='出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话”...
          │       │        │          └ Config(onebot=None, mirai=None, telegram=None, discord=None, http=HttpService(host='172.16.189.148', port=52131, debug=False)...
          │       │        └ <Task finished name='Task-111' coro=<handle_message.<locals>.request() done, defined at C:\bot\chatgpt-mirai-qq-bot\universal...
          │       └ <function wait_for at 0x000002D3A1B40280>
          └ <module 'asyncio' from 'C:\\Users\\Administrator\\Miniconda3\\envs\\chatgpt\\lib\\asyncio\\__init__.py'>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
           │   └ <method 'result' of '_asyncio.Task' objects>
           └ <Task finished name='Task-111' coro=<handle_message.<locals>.request() done, defined at C:\bot\chatgpt-mirai-qq-bot\universal...

  File "C:\bot\chatgpt-mirai-qq-bot\universal.py", line 236, in request
    await m.handle_respond_completed(session_id, prompt, respond)
          │ │                        │           │       └ <function handle_message.<locals>.respond at 0x000002D3CD407F40>
          │ │                        │           └ '你好'
          │ │                        └ '手动打码'
          │ └ <function MiddlewareRatelimit.handle_respond_completed at 0x000002D3CD2C9D80>
          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x000002D3CBF4FFA0>

  File "C:\bot\chatgpt-mirai-qq-bot\middlewares\ratelimit.py", line 27, in handle_respond_completed
    msg_id = session_id.split('-', 1)[1]
             │          └ <method 'split' of 'str' objects>
             └ '手动打码'

IndexError: list index out of range
2024-01-26 00:07:24.556 | INFO     | platforms.http_service:response:86 - Got response msg -> <class 'str'> -> 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说 的我就当作没看见。
list index out of range
2024-01-26 00:07:24.556 | DEBUG    | platforms.http_service:process_request:115 - Bot request 1706198843160 done.
