### ISSUE TITLE
[BUG] DOCKer部署无法启动

### ISSUE THREAD

**Issue by liu2-3zhi** [lss233/kirara-ai#1300]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
无法启动

chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.092 | INFO     | manager.bot:login_openai:364 - 正在登录第 1 个 OpenAI 账号
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.092 | INFO     | manager.bot:__login_openai_apikey:551 - 尝试使用 api_key 登录中...
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.093 | INFO     | manager.bot:__login_openai_apikey:555 - 当前检查的 API Key 为：sk-5jZxM******4UUi
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.093 | WARNING  | manager.bot:__login_openai_apikey:558 - 在查询 API 额度时遇到问题，请自行确认额度。
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.094 | SUCCESS  | manager.bot:login_openai:378 - 登录成功！
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.094 | SUCCESS  | manager.bot:login_openai:399 - 成功登录 1/1 个 OpenAI 账号！
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.094 | INFO     | manager.bot:login:182 - AI 类型：chatgpt-web - 可用账号： 0 个
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.095 | INFO     | manager.bot:login:182 - AI 类型：openai-api - 可用账号： 1 个
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.095 | INFO     | manager.bot:login:182 - AI 类型：poe-web - 可用账号： 0 个
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.095 | INFO     | manager.bot:login:182 - AI 类型：bing-cookie - 可用账号： 0 个
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.095 | INFO     | manager.bot:login:182 - AI 类型：bard-cookie - 可用账号： 0 个
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.095 | INFO     | manager.bot:login:182 - AI 类型：yiyan-cookie - 可用账号： 0 个
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.096 | INFO     | manager.bot:login:182 - AI 类型：xinghuo-cookie - 可用账号： 0 个
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.096 | INFO     | manager.bot:login:182 - AI 类型：chatglm-api - 可用账号： 0 个
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.097 | INFO     | manager.bot:login:182 - AI 类型：slack-accesstoken - 可用账号： 0 个
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.097 | INFO     | manager.bot:login:182 - AI 类型：gpt4free - 可用账号： 0 个
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.097 | INFO     | __main__:<module>:40 - 检测到 http 配置，将启动 http service 模式……
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.347 | ERROR    | utils.exithooks:foo:35 - 看样子程序似乎没有正常退出。
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.348 | ERROR    | utils.exithooks:foo:36 - cannot import name 'url_decode' from 'werkzeug.urls' (/usr/local/lib/python3.10/site-packages/werkzeug/urls.py)
chatgpt-qq-chatgpt-1     | NoneType: None
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.349 | ERROR    | utils.exithooks:foo:37 - 你可以在这里阅读常见问题的解决方案：
chatgpt-qq-chatgpt-1     | 2024-02-02 02:20:33.349 | ERROR    | utils.exithooks:foo:38 - https://github.com/lss233/chatgpt-mirai-qq-bot/issues/85
chatgpt-qq-chatgpt-1     | Exception ignored in atexit callback: <function foo at 0x7f42230775b0>
chatgpt-qq-chatgpt-1     | Traceback (most recent call last):
chatgpt-qq-chatgpt-1     |   File "/app/utils/exithooks.py", line 39, in foo
chatgpt-qq-chatgpt-1     |     raise hooks.exception
chatgpt-qq-chatgpt-1     |   File "/app/bot.py", line 41, in <module>
chatgpt-qq-chatgpt-1     |     from platforms.http_service import start_task
chatgpt-qq-chatgpt-1     |   File "/app/platforms/http_service.py", line 10, in <module>
chatgpt-qq-chatgpt-1     |     from quart import Quart, request
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.10/site-packages/quart/__init__.py", line 7, in <module>
chatgpt-qq-chatgpt-1     |     from .app import Quart
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.10/site-packages/quart/app.py", line 46, in <module>
chatgpt-qq-chatgpt-1     |     from .asgi import ASGIHTTPConnection, ASGILifespan, ASGIWebsocketConnection
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.10/site-packages/quart/asgi.py", line 29, in <module>
chatgpt-qq-chatgpt-1     |     from .debug import traceback_response
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.10/site-packages/quart/debug.py", line 8, in <module>
chatgpt-qq-chatgpt-1     |     from .wrappers import Response
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.10/site-packages/quart/wrappers/__init__.py", line 4, in <module>
chatgpt-qq-chatgpt-1     |     from .request import Body, Request
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.10/site-packages/quart/wrappers/request.py", line 23, in <module>
chatgpt-qq-chatgpt-1     |     from ..formparser import FormDataParser
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.10/site-packages/quart/formparser.py", line 23, in <module>
chatgpt-qq-chatgpt-1     |     from werkzeug.urls import url_decode
chatgpt-qq-chatgpt-1     | ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/usr/local/lib/python3.10/site-packages/werkzeug/urls.py)
chatgpt-qq-chatgpt-1 exited with code 1

**运行环境:**  
DOCK

**复现步骤**  
使用一键安装脚本部署即可

**Comment by Cal0rie** [comment]
[werkzeug.zip](https://github.com/lss233/chatgpt-mirai-qq-bot/files/14139053/werkzeug.zip)
把这个东西解压到./chatgpt-qq文件夹的werkzeug目录里

**Comment by liu2-3zhi** [comment]
为何不直接推送docker容器更新

**Comment by liu2-3zhi** [comment]
https://github.com/lss233/chatgpt-mirai-qq-bot/issues/1261

**Comment by suiyang5167** [comment]
> 为何不直接推送docker容器更新

+1

**Comment by liu2-3zhi** [comment]
test
