### ISSUE TITLE
[BUG] Poe无法解析p-b

### ISSUE THREAD

**Issue by Tianxiaorui9001** [lss233/kirara-ai#1309]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
chatgpt-installer.exe具体报错如下：
[2024-02-13 14:57:41.165] [info] 启动程序
2024-02-13 14:57:43.194 | SUCCESS  | config:scan_presets:565 - 检查预设：聊天 <==> presets/issue402.txt [成功]
2024-02-13 14:57:43.194 | SUCCESS  | config:scan_presets:565 - 检查预设：猫娘 <==> presets/catgirl.txt [成功]
2024-02-13 14:57:43.194 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl <==> ./presets\catgirl.txt [成功]
2024-02-13 14:57:43.194 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl_en <==> ./presets\catgirl_en.txt [成功]2024-02-13 14:57:43.194 | SUCCESS  | config:scan_presets:578 - 注册预设：issue402 <==> ./presets\issue402.txt [成功]
2024-02-13 14:57:43.194 | SUCCESS  | config:scan_presets:578 - 注册预设：预设模板 <==> ./presets\预设模板.txt [成功]
2024-02-13 14:57:43.289 | INFO     | manager.bot:__check_proxy:406 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2024-02-13 14:57:43.565 | SUCCESS  | manager.bot:__check_proxy:414 - [代理测试] 连接成功！
2024-02-13 14:57:43.565 | INFO     | manager.bot:login_poe:285 - 正在解析第 1 个 poe web 账号
2024-02-13 14:57:43.565 | INFO     | manager.bot:__check_proxy:406 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2024-02-13 14:57:43.855 | SUCCESS  | manager.bot:__check_proxy:414 - [代理测试] 连接成功！
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (1/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (2/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (3/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (4/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (5/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (6/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (7/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (8/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (9/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (10/10)...
2024-02-13 14:57:45.522 | ERROR    | manager.bot:login_poe:293 - 解析失败：
2024-02-13 14:57:45.524 | ERROR    | manager.bot:login_poe:294 - Failed to download https://poe.com too many times.
Traceback (most recent call last):

  File "C:\Users\tianxiaorui9001\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\bot.py", line 14, in <module>
    loop.run_until_complete(botManager.login())
    │    │                  │          └ <function BotManager.login at 0x000002D621477520>
    │    │                  └ <manager.bot.BotManager object at 0x000002D621490B20>
    │    └ <function BaseEventLoop.run_until_complete at 0x000002D6778A8AF0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\tianxiaorui9001\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000002D6790E96C0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\tianxiaorui9001\Miniconda3\envs\chatgpt\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\tianxiaorui9001\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000002D6778AA560>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\tianxiaorui9001\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002D67784D990>
    └ <Handle <TaskStepMethWrapper object at 0x000002D621639750>()>

  File "C:\Users\tianxiaorui9001\Miniconda3\envs\chatgpt\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000002D621639750>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000002D621639750>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000002D621639750>()>

  File "C:\Users\tianxiaorui9001\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\manager\bot.py", line 164, in login
    login_func()
    └ <bound method BotManager.login_poe of <manager.bot.BotManager object at 0x000002D621490B20>>

> File "C:\Users\tianxiaorui9001\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\manager\bot.py", line 288, in login_poe
    bot = PoeClient(token=account.p_b, proxy=account.proxy)
          │               │       │          │       └ 'http://127.0.0.1:7890'
          │               │       │          └ PoeCookieAuth(p_b='kiTtpEJply_qlPOUOQJuOA%3D%3D', proxy='http://127.0.0.1:7890')
          │               │       └ 'kiTtpEJply_qlPOUOQJuOA%3D%3D'
          │               └ PoeCookieAuth(p_b='kiTtpEJply_qlPOUOQJuOA%3D%3D', proxy='http://127.0.0.1:7890')
          └ <class 'poe.Client'>

  File "C:\Users\tianxiaorui9001\Miniconda3\envs\chatgpt\lib\site-packages\poe.py", line 150, in __init__
    self.connect_ws()
    │    └ <function Client.connect_ws at 0x000002D621047E20>
    └ <poe.Client object at 0x000002D62163A5C0>

  File "C:\Users\tianxiaorui9001\Miniconda3\envs\chatgpt\lib\site-packages\poe.py", line 411, in connect_ws
    self.setup_connection()
    │    └ <function Client.setup_connection at 0x000002D6210475B0>
    └ <poe.Client object at 0x000002D62163A5C0>

  File "C:\Users\tianxiaorui9001\Miniconda3\envs\chatgpt\lib\site-packages\poe.py", line 176, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
    │                │    └ <function Client.get_next_data at 0x000002D621047760>
    │                └ <poe.Client object at 0x000002D62163A5C0>
    └ <poe.Client object at 0x000002D62163A5C0>

  File "C:\Users\tianxiaorui9001\Miniconda3\envs\chatgpt\lib\site-packages\poe.py", line 218, in get_next_data
    r = request_with_retries(self.session.get, self.home_url)
        │                    │    │       │    │    └ 'https://poe.com'
        │                    │    │       │    └ <poe.Client object at 0x000002D62163A5C0>
        │                    │    │       └ <function Session.get at 0x000002D67B432B90>
        │                    │    └ <tls_client.sessions.Session object at 0x000002D62163A650>
        │                    └ <poe.Client object at 0x000002D62163A5C0>
        └ <function request_with_retries at 0x000002D67B445480>

  File "C:\Users\tianxiaorui9001\Miniconda3\envs\chatgpt\lib\site-packages\poe.py", line 80, in request_with_retries
    raise RuntimeError(f"Failed to download {url} too many times.")

RuntimeError: Failed to download https://poe.com too many times.
2024-02-13 14:57:45.544 | ERROR    | manager.bot:login_poe:296 - 所有 Poe 账号均解析失败！
2024-02-13 14:57:45.552 | SUCCESS  | manager.bot:login_poe:297 - 成功解析 0/1 个 poe web 账号！
2024-02-13 14:57:45.552 | ERROR    | manager.bot:login:169 - 没有登录成功的账号，程序无法启动！
[2024-02-13 14:57:45.718] [info] 按任意键退出...

已确定p-b是正确的，使用的是Clash 代理
测试poe.com可以正常打开，也可以正常聊天

**运行环境:**  
- 操作系统：Windows Server 2022 Datacenter
- Docker： 无（也可能是我不知道）
- 项目版本：2.5.3

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 启动chatgpt-installer.exe
2. 程序运行，报错

**预期行为**  
描述你认为正常情况下应该看见的情况
解析成功，正常运行

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by wingflex** [comment]
我也是这样，解决了吗

**Comment by ACCSCI** [comment]
还是没解决
