### ISSUE TITLE
[BUG] httpcore.ConnectError: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by Wangmomo667** [lss233/kirara-ai#529]
- [√] 我已看过 FAQ，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/94622958/229729026-3a45797c-a9ef-4601-ab9b-6d7dc704d7cb.png">
<img width="720" alt="image" src="https://user-images.githubusercontent.com/94622958/229729123-88f859fb-69f0-42ac-bb60-f0512f362272.png">

> gpt-chatgpt-1     | 2023-04-04 08:01:26.508 | INFO     | graia.ariadne.model:log:82 - 1279596549: [RECV][Meow(29897996)] -> 你好
gpt-chatgpt-1     | 2023-04-04 08:02:26.565 | ERROR    | graia.ariadne.util:loguru_exc_callback:76 - Exception:
gpt-chatgpt-1     | Traceback (most recent call last):
gpt-chatgpt-1     | 
gpt-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
gpt-chatgpt-1     |     yield
gpt-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/backends/sync.py", line 94, in connect_tcp
gpt-chatgpt-1     |     sock = socket.create_connection(
gpt-chatgpt-1     |            │      └ <function create_connection at 0x7f0b165fbc40>
gpt-chatgpt-1     |            └ <module 'socket' from '/usr/local/lib/python3.11/socket.py'>
gpt-chatgpt-1     |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
gpt-chatgpt-1     |     raise exceptions[0]
gpt-chatgpt-1     |           └ []
gpt-chatgpt-1     |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
gpt-chatgpt-1     |     sock.connect(sa)
gpt-chatgpt-1     |     │    │       └ ('2606:4700:3030::ac43:9da5', 443, 0, 0)
gpt-chatgpt-1     |     │    └ <method 'connect' of '_socket.socket' objects>
gpt-chatgpt-1     |     └ <socket.socket [closed] fd=-1, family=10, type=1, proto=6>
gpt-chatgpt-1     | 
gpt-chatgpt-1     | OSError: [Errno 99] Cannot assign requested address
gpt-chatgpt-1     | 
gpt-chatgpt-1     | 
gpt-chatgpt-1     | During handling of the above exception, another exception occurred:
gpt-chatgpt-1     | 
gpt-chatgpt-1     | 
gpt-chatgpt-1     | Traceback (most recent call last):
gpt-chatgpt-1     | 
gpt-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
gpt-chatgpt-1     |     yield
gpt-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 218, in handle_request
gpt-chatgpt-1     |     resp = self._pool.handle_request(req)
gpt-chatgpt-1     |            │    │     │              └ <Request [b'GET']>
gpt-chatgpt-1     |            │    │     └ <function ConnectionPool.handle_request at 0x7f0b14764360>
gpt-chatgpt-1     |            │    └ <httpcore.ConnectionPool object at 0x7f0b1300fc90>
gpt-chatgpt-1     |            └ <httpx.HTTPTransport object at 0x7f0b11308c10>
gpt-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
gpt-chatgpt-1     |     raise exc
gpt-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
gpt-chatgpt-1     |     response = connection.handle_request(request)
gpt-chatgpt-1     |                │          │              └ <Request [b'GET']>
gpt-chatgpt-1     |                │          └ <function HTTPConnection.handle_request at 0x7f0b148f1080>
gpt-chatgpt-1     |                └ <HTTPConnection [CONNECTION FAILED]>
gpt-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
gpt-chatgpt-1     |     raise exc
gpt-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
gpt-chatgpt-1     |     stream = self._connect(request)
gpt-chatgpt-1     |              │    │        └ <Request [b'GET']>
gpt-chatgpt-1     |              │    └ <function HTTPConnection._connect at 0x7f0b14747600>
gpt-chatgpt-1     |              └ <HTTPConnection [CONNECTION FAILED]>
gpt-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 111, in _connect
gpt-chatgpt-1     |     stream = self._network_backend.connect_tcp(**kwargs)
gpt-chatgpt-1     |              │    │                │             └ {'host': 'edge.churchless.tech', 'port': 443, 'local_address': None, 'timeout': 30}
gpt-chatgpt-1     |              │    │                └ <function SyncBackend.connect_tcp at 0x7f0b148f31a0>
gpt-chatgpt-1     |              │    └ <httpcore.backends.sync.SyncBackend object at 0x7f0b11308bd0>
gpt-chatgpt-1     |              └ <HTTPConnection [CONNECTION FAILED]>
gpt-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/backends/sync.py", line 93, in connect_tcp
gpt-chatgpt-1     |     with map_exceptions(exc_map):
gpt-chatgpt-1     |          │              └ {<class 'TimeoutError'>: <class 'httpcore.ConnectTimeout'>, <class 'OSError'>: <class 'httpcore.ConnectError'>}
gpt-chatgpt-1     |          └ <function map_exceptions at 0x7f0b148f0b80>
gpt-chatgpt-1     |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
gpt-chatgpt-1     |     self.gen.throw(typ, value, traceback)
gpt-chatgpt-1     |     │    │   │     │    │      └ <traceback object at 0x7f0b1130b680>
gpt-chatgpt-1     |     │    │   │     │    └ OSError(99, 'Cannot assign requested address')
gpt-chatgpt-1     |     │    │   │     └ <class 'OSError'>
gpt-chatgpt-1     |     │    │   └ <method 'throw' of 'generator' objects>
gpt-chatgpt-1     |     │    └ <generator object map_exceptions at 0x7f0b112f4d40>
gpt-chatgpt-1     |     └ <contextlib._GeneratorContextManager object at 0x7f0b1130b590>
gpt-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
gpt-chatgpt-1     |     raise to_exc(exc)
gpt-chatgpt-1     |           └ <class 'httpcore.ConnectError'>
gpt-chatgpt-1     | 
gpt-chatgpt-1     | httpcore.ConnectError: [Errno 99] Cannot assign requested address
gpt-chatgpt-1     | 

账号解析成功，未使用代理，使用`https://edgeservices.bing.com/edgesvc/turing/conversation/create`接入点，未报其他错误但不回复信息

**Comment by lss233** [comment]
根据报错来看是无法建立 socket 连接，这可能是你的网络环境异常导致的，建议检查一下。

**Comment by Wangmomo667** [comment]
> 根据报错来看是无法建立 socket 连接，这可能是你的网络环境异常导致的，建议检查一下。

谢谢大佬，有没有什么基本的排查方式？我使用了接入点是否还需要配置代理？
