### ISSUE TITLE
[BUG] 作图功能可否加入太乙Stable diffusion的支持？因为可以直接用中文作为提示词作图

### ISSUE THREAD

**Issue by realdenis** [lss233/kirara-ai#711]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [X] 我已看过其他 issue，他们不能解决我的问题 
- [X] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
作图（txt2img）功能，如使用太乙版的Stable diffusion（https://github.com/IDEA-CCNL/stable-diffusion-webui），就会报404错误（已确认路径无误，浏览器可以正常访问）；如果用AUTOMATC1111版Stable diffusion则一切正常。

**运行环境:**  
- 操作系统：ubuntu 22.04.1
- Docker： 20.10.21
- 项目版本：2.4.2.1

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 在QQ中给出作图指令即可触发
备注：Stable diffusion运行时的添加参数统一为--xformers --nowebui

**预期行为**  
按照指令作图

**截图**  
![WX20230427-113211@2x](https://user-images.githubusercontent.com/60921346/234753183-99e21643-1d7a-4591-af5d-18e73de4d3b8.png)
![WX20230427-113353@2x](https://user-images.githubusercontent.com/60921346/234753911-a573fd2b-a1e7-4a61-b2f1-030208b2ae87.png)
=======================chatglm-6b-engineering项目-==========================
![WX20230427-113925@2x](https://user-images.githubusercontent.com/60921346/234753739-d13a4d19-d835-44a5-bf3b-a462d0e6a2a4.png)

**其他内容**  
相同设置下，用chatglm-6b-engineering这个项目（https://github.com/LemonQu-GIT/ChatGLM-6B-Engineering）的界面可以调用太乙版Stable diffusion进行作图，如上述最后一张截图所示。

**Comment by lss233** [comment]
你启动 sd 的时候加上 `--api` 参数试试？

**Comment by realdenis** [comment]
> 你启动 sd 的时候加上 `--api` 参数试试？

试过了，也不行……

**Comment by lss233** [comment]
我对比了你发过来的两个项目的代码，我这里调用 sdwebui 的接口方式和 你发的那个项目其实是一样的。  

唯一的可能性就是你的 sdwebui 启动的时候没开启接口了。 你要不然发一下日志我看看？

**Comment by realdenis** [comment]
> 我对比了你发过来的两个项目的代码，我这里调用 sdwebui 的接口方式和 你发的那个项目其实是一样的。
> 
> 唯一的可能性就是你的 sdwebui 启动的时候没开启接口了。 你要不然发一下日志我看看？



![WX20230427-221846](https://user-images.githubusercontent.com/60921346/234891352-bf3fa35e-b7c5-4284-90bf-a19f1e689d09.png)
上图是我用chatglm-6b-engineering项目(https://github.com/LemonQu-GIT/ChatGLM-6B-Engineering）和本项目分别调用太乙Stable diffusion时，在SD console下的显示。chatglm-6b-engineering调用结果就是 200 ok，本项目调用时就是404 Not Found。

以下是本项目调用太乙Stable diffusion时给出的报错日志：

2023-04-27 14:16:15.888 | ERROR    | universal:handle_message:250 - 


Traceback (most recent call last):




  File "/app/conversation.py", line 165, in ask


    images = await self.drawing_adapter.text_to_img(prompt)


                   │    │               │           └ '一只鸡'


                   │    │               └ <function SDWebUI.text_to_img at 0x7fb32d0c8ae0>


                   │    └ <drawing.sdwebui.SDWebUI object at 0x7fb32c9f16d0>


                   └ <conversation.ConversationContext object at 0x7fb32c9f1ed0>




  File "/app/drawing/sdwebui.py", line 55, in text_to_img


    resp.raise_for_status()


    │    └ <function Response.raise_for_status at 0x7fb33000aca0>


    └ <Response [404 Not Found]>




  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 749, in raise_for_status


    raise HTTPStatusError(message, request=request, response=self)


          │               │                │                 └ <Response [404 Not Found]>


          │               │                └ <Request('POST', 'http://127.0.0.1:7861/sdapi/v1/txt2img')>


          │               └ "Client error '404 Not Found' for url 'http://127.0.0.1:7861/sdapi/v1/txt2img'\nFor more information check: https://httpstatu...


          └ <class 'httpx.HTTPStatusError'>




httpx.HTTPStatusError: Client error '404 Not Found' for url 'http://127.0.0.1:7861/sdapi/v1/txt2img'


For more information check: https://httpstatuses.com/404






The above exception was the direct cause of the following exception:






Traceback (most recent call last):




  File "/app/bot.py", line 50, in <module>


    loop.run_until_complete(asyncio.gather(*bots))


    │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at /app/platforms/onebot_bot.py:354> wait_for=<_GatheringFuture pendi...


    │    │                  │       └ <function gather at 0x7fb3318d05e0>


    │    │                  └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>


    │    └ <function BaseEventLoop.run_until_complete at 0x7fb3318e13a0>


    └ <_UnixSelectorEventLoop running=True closed=False debug=False>




  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete


    self.run_forever()


    │    └ <function BaseEventLoop.run_forever at 0x7fb3318e1300>


    └ <_UnixSelectorEventLoop running=True closed=False debug=False>


  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever


    self._run_once()


    │    └ <function BaseEventLoop._run_once at 0x7fb3318e3100>


    └ <_UnixSelectorEventLoop running=True closed=False debug=False>


  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once


    handle._run()


    │      └ <function Handle._run at 0x7fb331e3c040>


    └ <Handle Task.task_wakeup(<Future finished result=None>)>


  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run


    self._context.run(self._callback, *self._args)


    │    │            │    │           │    └ <member '_args' of 'Handle' objects>


    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>


    │    │            │    └ <member '_callback' of 'Handle' objects>


    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>


    │    └ <member '_context' of 'Handle' objects>


    └ <Handle Task.task_wakeup(<Future finished result=None>)>




  File "/app/platforms/onebot_bot.py", line 151, in _


    await handle_message(


          └ <function handle_message at 0x7fb32c9fce00>




> File "/app/universal.py", line 248, in handle_message


    await action(session_id, message.strip(), conversation_context, respond)


          │      │           │       │        │                     └ <function handle_message.<locals>.respond at 0x7fb32ca24040>


          │      │           │       │        └ None


          │      │           │       └ <method 'strip' of 'str' objects>


          │      │           └ '画一只鸡'


          │      └ 'friend-284094627'


          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fb32aa55bc0>




  File "/app/universal.py", line 77, in call


    await m.handle_request(session_id, message, respond, conversation_context, n)


          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fb32aa55940>


          │ │              │           │        │        └ None


          │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fb32ca24040>


          │ │              │           └ '画一只鸡'


          │ │              └ 'friend-284094627'


          │ └ <function MiddlewareConcurrentLock.handle_request at 0x7fb32c9fd6c0>


          └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x7fb32c9f6290>




  File "/app/middlewares/concurrentlock.py", line 43, in handle_request


    await action(session_id, prompt, conversation_context, respond)


          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7fb32ca24040>


          │      │           │       └ None


          │      │           └ '画一只鸡'


          │      └ 'friend-284094627'


          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fb32aa55940>




  File "/app/universal.py", line 77, in call


    await m.handle_request(session_id, message, respond, conversation_context, n)


          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fb32c9ff420>


          │ │              │           │        │        └ None


          │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fb32ca24040>


          │ │              │           └ '画一只鸡'


          │ │              └ 'friend-284094627'


          │ └ <function Middleware.handle_request at 0x7fb32c9fc900>


          └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x7fb32c9f6590>




  File "/app/middlewares/middleware.py", line 9, in handle_request


    await action(session_id, prompt, conversation_context, respond)


          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7fb32ca24040>


          │      │           │       └ None


          │      │           └ '画一只鸡'


          │      └ 'friend-284094627'


          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fb32c9ff420>




  File "/app/universal.py", line 77, in call


    await m.handle_request(session_id, message, respond, conversation_context, n)


          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fb32c9ffec0>


          │ │              │           │        │        └ None


          │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fb32ca24040>


          │ │              │           └ '画一只鸡'


          │ │              └ 'friend-284094627'


          │ └ <function MiddlewareRatelimit.handle_request at 0x7fb32c9fcb80>


          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x7fb32c9f6190>




  File "/app/middlewares/ratelimit.py", line 23, in handle_request


    await action(session_id, prompt, conversation_context, respond)


          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7fb32ca24040>


          │      │           │       └ None


          │      │           └ '画一只鸡'


          │      └ 'friend-284094627'


          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fb32c9ffec0>




  File "/app/universal.py", line 77, in call


    await m.handle_request(session_id, message, respond, conversation_context, n)


          │ │              │           │        │        │                     └ <function handle_message.<locals>.request at 0x7fb32c9ffce0>


          │ │              │           │        │        └ None


          │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fb32ca24040>


          │ │              │           └ '画一只鸡'


          │ │              └ 'friend-284094627'


          │ └ <function MiddlewareTimeout.handle_request at 0x7fb32c9fd800>


          └ <middlewares.timeout.MiddlewareTimeout object at 0x7fb32c9f1090>




  File "/app/middlewares/timeout.py", line 27, in handle_request


    await asyncio.wait_for(coro_task, config.response.max_timeout)


          │       │        │          │      │        └ 600.0


          │       │        │          │      └ Response(mode='mixed', buffer_delay=15, default_ai='chatglm-api', error_format='出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚...


          │       │        │          └ Config(onebot=Onebot(qq=3563179436, manager_qq=3563179436, reverse_ws_host='127.0.0.1', reverse_ws_port=8566), mirai=None, te...


          │       │        └ <Task finished name='Task-6973' coro=<handle_message.<locals>.request() done, defined at /app/universal.py:117> exception=Dra...


          │       └ <function wait_for at 0x7fb3318d0040>


          └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>




  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 479, in wait_for


    return fut.result()


           │   └ <method 'result' of '_asyncio.Task' objects>


           └ <Task finished name='Task-6973' coro=<handle_message.<locals>.request() done, defined at /app/universal.py:117> exception=Dra...




  File "/app/universal.py", line 228, in request


    async for rendered in task:


                          └ <async_generator object retry.<locals>.decorator.<locals>.wrapper at 0x7fb32d2676e0>




  File "/app/utils/retry.py", line 21, in wrapper


    async for result in func(*args, **kwargs):


                        │     │       └ {'prompt': '画一只鸡', 'chain': MessageChain([Plain(text='画一只鸡')]), 'name': 'realdenis'}


                        │     └ (<conversation.ConversationContext object at 0x7fb32c9f1ed0>,)


                        └ <function ConversationContext.ask at 0x7fb32c9fc220>




  File "/app/conversation.py", line 169, in ask


    raise DrawingFailedException from e


          └ <class 'exceptions.DrawingFailedException'>




exceptions.DrawingFailedException


2023-04-27 14:16:15.896 | DEBUG    | platforms.onebot_bot:respond:112 - [OneBot] 尝试发送消息：画图失败！原因： Client error '404 Not Found' for url 'http://127.0.0.1:7861/sdapi/v1/txt2img'


For more information check: https://httpstatuses.com/404


2023-04-27 14:16:15.897 | DEBUG    | middlewares.timeout:on_respond:40 - [Timeout] 取消计时……
