### ISSUE TITLE
[BUG] 请填写标题

### ISSUE THREAD

**Issue by TaoismDeepLake** [lss233/kirara-ai#812]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
2023-05-14 18:26:29.281 | ERROR    | manager.bot:login_openai:260 - 未知错误：
2023-05-14 18:26:29.284 | ERROR    | manager.bot:login_openai:261 - Client error '404 Not Found' for url 'https://bypass.churchless.tech/api/conversations?offset=0&limit=1'
For more information check: https://httpstatuses.com/404
Traceback (most recent call last):

  File "C:\qqrobot\Windows-quickstart-refs.tags.v2.3.3\chatgpt\bot.py", line 16, in <module>
    loop.run_until_complete(botManager.login())
    │    │                  │          └ <function BotManager.login at 0x0000019C0632C680>
    │    │                  └ <manager.bot.BotManager object at 0x0000019C0634BD50>
    │    └ <function BaseEventLoop.run_until_complete at 0x0000019C041D79C0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x0000019C0745FC10>()>

  File "C:\qqrobot\Windows-quickstart-refs.tags.v2.3.3\chatgpt\manager\bot.py", line 112, in login
    await self.login_openai()
          │    └ <function BotManager.login_openai at 0x0000019C0632D120>
          └ <manager.bot.BotManager object at 0x0000019C0634BD50>

> File "C:\qqrobot\Windows-quickstart-refs.tags.v2.3.3\chatgpt\manager\bot.py", line 237, in login_openai
    bot = await self.__login_V1(account)
                │               └ OpenAIAccessTokenAuth(mode='browserless', proxy='http://127.0.0.1:7990', driver_exec_path=None, browser_exec_path=None, conve...
                └ <manager.bot.BotManager object at 0x0000019C0634BD50>

  File "C:\qqrobot\Windows-quickstart-refs.tags.v2.3.3\chatgpt\manager\bot.py", line 347, in __login_V1
    if await __V1_check_auth():

  File "C:\qqrobot\Windows-quickstart-refs.tags.v2.3.3\chatgpt\manager\bot.py", line 335, in __V1_check_auth
    await bot.get_conversations(0, 1)
          │   └ <function AsyncChatbot.get_conversations at 0x0000019C06306E80>
          └ <revChatGPT.V1.AsyncChatbot object at 0x0000019C06367F90>

  File "C:\qqrobot\Windows-quickstart-refs.tags.v2.3.3\chatgpt\python3.11\Lib\site-packages\revChatGPT\V1.py", line 798, in get_conversations
    self.__check_response(response)
    │                     └ <Response [404 Not Found]>
    └ <revChatGPT.V1.AsyncChatbot object at 0x0000019C06367F90>
  File "C:\qqrobot\Windows-quickstart-refs.tags.v2.3.3\chatgpt\python3.11\Lib\site-packages\revChatGPT\V1.py", line 873, in __check_response
    response.raise_for_status()
    │        └ <function Response.raise_for_status at 0x0000019C059A8720>
    └ <Response [404 Not Found]>
  File "C:\qqrobot\Windows-quickstart-refs.tags.v2.3.3\chatgpt\python3.11\Lib\site-packages\httpx\_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
          │               │                │                 └ <Response [404 Not Found]>
          │               │                └ <Request('GET', 'https://bypass.churchless.tech/api/conversations?offset=0&limit=1')>
          │               └ "Client error '404 Not Found' for url 'https://bypass.churchless.tech/api/conversations?offset=0&limit=1'\nFor more informati...
          └ <class 'httpx.HTTPStatusError'>

httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://bypass.churchless.tech/api/conversations?offset=0&limit=1'
For more information check: https://httpstatuses.com/404

**运行环境:**  
- 操作系统：windows server 2016
- Docker： ？
- 项目版本 2.3.3

**复现步骤**  
描述你是如何触发这个 BUG 的
1.填写openai的key，然后正常启动gpt机器人。

**预期行为**  
应该正常通过或者说到底什么问题

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
请使用最新版，然后删除  browserless_endpoint 设置。
