### ISSUE TITLE
[BUG] 用户访问被限制

### ISSUE THREAD

**Issue by Laurc2004** [lss233/kirara-ai#872]
**提交 issue 前，请先确认：**
- [] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：Windows10
- Docker： ？
- 项目版本：2.5.1

**复现步骤**  
日志
[2023-05-23 20:31:06,117] 127.0.0.1:9336 GET /ws 1.1 101 - 0
2023-05-23 20:32:05.096 | DEBUG    | platforms.onebot_bot:_:181 - 群聊消息：[CQ:at,qq=1650706324] 你谁
2023-05-23 20:32:05.128 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
2023-05-23 20:32:05.128 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2023-05-23 20:32:05.128 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……
2023-05-23 20:32:07.866 | ERROR    | universal:handle_message:295 - 用户访问被限制
Traceback (most recent call last):

  File "C:\Users\Liu\Desktop\gpt\chatgpt\bot.py", line 54, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at C:\Users\Liu\Desktop\gpt\chatgpt\platforms\onebot_bot.py:356> wait...
    │    │                  │       └ <function gather at 0x000002C750EF2520>
    │    │                  └ <module 'asyncio' from 'C:\\Users\\Liu\\Desktop\\gpt\\python3.11\\python311.zip\\asyncio\\__init__.pyc'>
    │    └ <function BaseEventLoop.run_until_complete at 0x000002C750F13380>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\Liu\Desktop\gpt\chatgpt\platforms\onebot_bot.py", line 183, in _
    await handle_message(
          └ <function handle_message at 0x000002C7551727A0>

> File "C:\Users\Liu\Desktop\gpt\chatgpt\universal.py", line 269, in handle_message
    await action(session_id, message.strip(), conversation_context, respond)
          │      │           │       │        │                     └ <function handle_message.<locals>.respond at 0x000002C75533B9C0>
          │      │           │       │        └ None
          │      │           │       └ <method 'strip' of 'str' objects>
          │      │           └ '你谁'
          │      └ 'group-787020629'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002C75533BF60>

  File "C:\Users\Liu\Desktop\gpt\chatgpt\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002C75533BEC0>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002C75533B9C0>
          │ │              │           └ '你谁'
          │ │              └ 'group-787020629'
          │ └ <function MiddlewareConcurrentLock.handle_request at 0x000002C7553391C0>
          └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x000002C755335310>

  File "C:\Users\Liu\Desktop\gpt\chatgpt\middlewares\concurrentlock.py", line 43, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x000002C75533B9C0>
          │      │           │       └ None
          │      │           └ '你谁'
          │      └ 'group-787020629'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002C75533BEC0>

  File "C:\Users\Liu\Desktop\gpt\chatgpt\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002C75533BE20>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002C75533B9C0>
          │ │              │           └ '你谁'
          │ │              └ 'group-787020629'
          │ └ <function Middleware.handle_request at 0x000002C755338680>
          └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x000002C755335390>

  File "C:\Users\Liu\Desktop\gpt\chatgpt\middlewares\middleware.py", line 9, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x000002C75533B9C0>
          │      │           │       └ None
          │      │           └ '你谁'
          │      └ 'group-787020629'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002C75533BE20>

  File "C:\Users\Liu\Desktop\gpt\chatgpt\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002C75533BD80>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002C75533B9C0>
          │ │              │           └ '你谁'
          │ │              └ 'group-787020629'
          │ └ <function MiddlewareRatelimit.handle_request at 0x000002C754AC1300>
          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x000002C755335350>

  File "C:\Users\Liu\Desktop\gpt\chatgpt\middlewares\ratelimit.py", line 23, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x000002C75533B9C0>
          │      │           │       └ None
          │      │           └ '你谁'
          │      └ 'group-787020629'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x000002C75533BD80>

  File "C:\Users\Liu\Desktop\gpt\chatgpt\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.request at 0x000002C75533BA60>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x000002C75533B9C0>
          │ │              │           └ '你谁'
          │ │              └ 'group-787020629'
          │ └ <function MiddlewareTimeout.handle_request at 0x000002C755339260>
          └ <middlewares.timeout.MiddlewareTimeout object at 0x000002C7542F9590>

  File "C:\Users\Liu\Desktop\gpt\chatgpt\middlewares\timeout.py", line 27, in handle_request
    await asyncio.wait_for(coro_task, config.response.max_timeout)
          │       │        │          │      │        └ 600.0
          │       │        │          │      └ Response(mode='mixed', buffer_delay=15, default_ai='yiyan', error_format='出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或 者发送 “回滚对话” 来回...
          │       │        │          └ Config(onebot=Onebot(qq=1650706324, manager_qq=939688743, reverse_ws_host='0.0.0.0', reverse_ws_port=8566), mirai=None, teleg...
          │       │        └ <Task finished name='Task-36' coro=<handle_message.<locals>.request() done, defined at C:\Users\Liu\Desktop\gpt\chatgpt\unive...
          │       └ <function wait_for at 0x000002C750EF1F80>
          └ <module 'asyncio' from 'C:\\Users\\Liu\\Desktop\\gpt\\python3.11\\python311.zip\\asyncio\\__init__.pyc'>

  File "asyncio\tasks.py", line 479, in wait_for
    for f in todo:

  File "C:\Users\Liu\Desktop\gpt\chatgpt\universal.py", line 222, in request
    async for rendered in task:
                          └ <async_generator object retry.<locals>.decorator.<locals>.wrapper at 0x000002C7552CCFB0>

  File "C:\Users\Liu\Desktop\gpt\chatgpt\utils\retry.py", line 21, in wrapper
    async for result in func(*args, **kwargs):
                        │     │       └ {'prompt': '你谁', 'chain': MessageChain([Plain(text='Unsupported')]), 'name': '港岛妹夫'}
                        │     └ (<conversation.ConversationContext object at 0x000002C7553ADCD0>,)
                        └ <function ConversationContext.ask at 0x000002C755307EC0>

  File "C:\Users\Liu\Desktop\gpt\chatgpt\conversation.py", line 187, in ask
    async for item in self.adapter.ask(prompt):
                      │    │       │   └ '你谁'
                      │    │       └ <function YiyanAdapter.ask at 0x000002C755171C60>
                      │    └ <adapter.baidu.yiyan.YiyanAdapter object at 0x000002C7553ADD50>
                      └ <conversation.ConversationContext object at 0x000002C7553ADCD0>

  File "C:\Users\Liu\Desktop\gpt\chatgpt\adapter\baidu\yiyan.py", line 126, in ask
    self.__check_response(req.json())
    │                     │   └ <function Response.json at 0x000002C7527B4D60>
    │                     └ <Response [200 OK]>
    └ <adapter.baidu.yiyan.YiyanAdapter object at 0x000002C7553ADD50>

  File "C:\Users\Liu\Desktop\gpt\chatgpt\adapter\baidu\yiyan.py", line 182, in __check_response
    raise Exception(resp['msg'])
                    └ {'code': 40005, 'msg': '用户访问被限制', 'data': None, 'logId': '118000002296985164'}

Exception: 用户访问被限制

**Comment by lss233** [comment]
重复：#799
