### ISSUE TITLE
docker安装后不能运行

### ISSUE THREAD

**Issue by Jingle-Pan** [lss233/kirara-ai#926]
2023-06-07 00:58:00.789 | ERROR    | config:load_config:202 - [Errno 2] No such file or directory: 'config.cfg'
Traceback (most recent call last):
  File "/app/bot.py", line 25, in <module>
    import chatbot
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/chatbot.py", line 12, in <module>
    from manager import BotManager, BotInfo
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/manager.py", line 15, in <module>
    config = Config.load_config()
             │      └ <staticmethod object at xxxxxxxxx>
             └ <class 'config.Config'>
> File "/app/config.py", line 196, in load_config
    with open("config.cfg", "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.cfg'
2023-06-07 00:58:00.793 | ERROR    | config:load_config:203 - 配置文件有误，请重新修改！

**Comment by L-Lynxu** [comment]
缺少 config.cfg
/app 路径下没有找到 config.cfg
是群晖 docker 吗，我怀疑你做了文件映射，但是没有把 config.cfg 放到映射位置（因为我就干过这事）

**Comment by Jingle-Pan** [comment]
> 缺少 config.cfg /app 路径下没有找到 config.cfg 是群晖 docker 吗，我怀疑你做了文件映射，但是没有把 config.cfg 放到映射位置（因为我就干过这事）

是Windows安装里的docker
