### ISSUE TITLE
[BUG] 请填写标题

### ISSUE THREAD

**Issue by Zhuuufyuu** [lss233/kirara-ai#954]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况
使用access_token登陆时一次报错OpenAI:ping (code:404)一次报错未知错误
**运行环境:
- 操作系统：window
- Docker： ？
- 项目版本：v2.5.2

**复现步骤**  
描述你是如何触发这个 BUG 的
1.正常修改config.cfg文件后启动ChatGPT.cmd然后报错

**预期行为**  
正常启动

**截图**  
Active code page: 65001
2023-06-13 18:00:15.655 | SUCCESS  | config:scan_presets:557 - 检查预设：聊天 <==> presets/issue402.txt [成功]
2023-06-13 18:00:15.656 | SUCCESS  | config:scan_presets:557 - 检查预设：猫娘 <==> presets/catgirl.txt [成功]
2023-06-13 18:00:15.657 | SUCCESS  | config:scan_presets:570 - 注册预设：bing <==> ./presets\assistant\bing.txt [成功]
2023-06-13 18:00:15.658 | SUCCESS  | config:scan_presets:570 - 注册预设：dan <==> ./presets\assistant\dan.txt [成功]
2023-06-13 18:00:15.659 | SUCCESS  | config:scan_presets:570 - 注册预设：debater <==> ./presets\assistant\debater.txt [成功]
2023-06-13 18:00:15.659 | SUCCESS  | config:scan_presets:570 - 注册预设：kp <==> ./presets\assistant\kp.txt [成功]
2023-06-13 18:00:15.660 | SUCCESS  | config:scan_presets:570 - 注册预设：lawyer <==> ./presets\assistant\lawyer.txt [成功]
2023-06-13 18:00:15.661 | SUCCESS  | config:scan_presets:570 - 注册预设：long <==> ./presets\assistant\long.txt [成功]
2023-06-13 18:00:15.661 | SUCCESS  | config:scan_presets:570 - 注册预设：Lss233 <==> ./presets\assistant\Lss233.txt [成功]
2023-06-13 18:00:15.662 | SUCCESS  | config:scan_presets:570 - 注册预设：novelist <==> ./presets\assistant\novelist.txt [成功]
2023-06-13 18:00:15.663 | SUCCESS  | config:scan_presets:570 - 注册预设：poet <==> ./presets\assistant\poet.txt [成功]
2023-06-13 18:00:15.663 | SUCCESS  | config:scan_presets:570 - 注册预设：shineisheji <==> ./presets\assistant\shineisheji.txt [成功]
2023-06-13 18:00:15.664 | SUCCESS  | config:scan_presets:570 - 注册预设：catgirl <==> ./presets\role-play\catgirl.txt [成功]
2023-06-13 18:00:15.665 | SUCCESS  | config:scan_presets:570 - 注册预设：cixiaogui <==> ./presets\role-play\cixiaogui.txt [成功]
2023-06-13 18:00:15.665 | SUCCESS  | config:scan_presets:570 - 注册预设：crazy <==> ./presets\role-play\crazy.txt [成功]2023-06-13 18:00:15.666 | SUCCESS  | config:scan_presets:570 - 注册预设：debatestick <==> ./presets\role-play\debatestick.txt [成功]
2023-06-13 18:00:15.667 | SUCCESS  | config:scan_presets:570 - 注册预设：dingzhen <==> ./presets\role-play\dingzhen.txt [成功]
2023-06-13 18:00:15.667 | SUCCESS  | config:scan_presets:570 - 注册预设：DJ <==> ./presets\role-play\DJ.txt [成功]
2023-06-13 18:00:15.668 | SUCCESS  | config:scan_presets:570 - 注册预设：ERNIE <==> ./presets\role-play\ERNIE.txt [成功]2023-06-13 18:00:15.668 | SUCCESS  | config:scan_presets:570 - 注册预设：gaoqiqiang <==> ./presets\role-play\gaoqiqiang.txt [成功]
2023-06-13 18:00:15.671 | SUCCESS  | config:scan_presets:570 - 注册预设：hanli <==> ./presets\role-play\hanli.txt [成功]2023-06-13 18:00:15.672 | SUCCESS  | config:scan_presets:570 - 注册预设：huxijin <==> ./presets\role-play\huxijin.txt [成功]
2023-06-13 18:00:15.673 | SUCCESS  | config:scan_presets:570 - 注册预设：ikun <==> ./presets\role-play\ikun.txt [成功]
2023-06-13 18:00:15.673 | SUCCESS  | config:scan_presets:570 - 注册预设：jiabaili <==> ./presets\role-play\jiabaili.txt [成功]
2023-06-13 18:00:15.674 | SUCCESS  | config:scan_presets:570 - 注册预设：linruolan <==> ./presets\role-play\linruolan.txt [成功]
2023-06-13 18:00:15.675 | SUCCESS  | config:scan_presets:570 - 注册预设：MOSS <==> ./presets\role-play\MOSS.txt [成功]
2023-06-13 18:00:15.676 | SUCCESS  | config:scan_presets:570 - 注册预设：PG13succubus <==> ./presets\role-play\PG13succubus.txt [成功]
2023-06-13 18:00:15.677 | SUCCESS  | config:scan_presets:570 - 注册预设：powanlang <==> ./presets\role-play\powanlang.txt [成功]
2023-06-13 18:00:15.678 | SUCCESS  | config:scan_presets:570 - 注册预设：TsundereCatgirl <==> ./presets\role-play\TsundereCatgirl.txt [成功]
2023-06-13 18:00:15.679 | SUCCESS  | config:scan_presets:570 - 注册预设：welldone <==> ./presets\role-play\welldone.txt [成功]
2023-06-13 18:00:15.680 | SUCCESS  | config:scan_presets:570 - 注册预设：yutao <==> ./presets\role-play\yutao.txt [成功]2023-06-13 18:00:15.681 | SUCCESS  | config:scan_presets:570 - 注册预设：zhangweiwei <==> ./presets\role-play\zhangweiwei.txt [成功]
2023-06-13 18:00:15.682 | ERROR    | config:scan_presets:567 - 注册预设：dan <==> ./presets\utils\dan.txt [失败：关键词已存在]
2023-06-13 18:00:15.683 | ERROR    | config:scan_presets:567 - 注册预设：catgirl <==> ./presets\catgirl.txt [失败：关键词已存在]
2023-06-13 18:00:15.684 | SUCCESS  | config:scan_presets:570 - 注册预设：catgirl_en <==> ./presets\catgirl_en.txt [成功]2023-06-13 18:00:15.684 | SUCCESS  | config:scan_presets:570 - 注册预设：issue402 <==> ./presets\issue402.txt [成功]
2023-06-13 18:00:15.687 | SUCCESS  | config:scan_presets:570 - 注册预设：预设模板 <==> ./presets\预设模板.txt [成功]
2023-06-13 18:00:15.736 | INFO     | manager.bot:__check_proxy:393 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2023-06-13 18:00:15.861 | SUCCESS  | manager.bot:__check_proxy:401 - [代理测试] 连接成功！
2023-06-13 18:00:15.862 | INFO     | manager.bot:login:130 - 当前的 browserless_endpoint 为：https://bypass.churchless.tech/api/
2023-06-13 18:00:15.863 | INFO     | manager.bot:login:146 - 当前的 api_endpoint 为：https://api.openai.com/v1
2023-06-13 18:00:15.863 | INFO     | manager.bot:login_openai:329 - 正在登录第 1 个 OpenAI 账号
2023-06-13 18:00:15.864 | INFO     | manager.bot:__login_V1:419 - 模式：无浏览器登录
2023-06-13 18:00:15.865 | INFO     | manager.bot:__check_proxy:393 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2023-06-13 18:00:15.927 | SUCCESS  | manager.bot:__check_proxy:401 - [代理测试] 连接成功！
2023-06-13 18:00:15.928 | INFO     | manager.bot:__login_V1:469 - 尝试使用 access_token 登录中...
2023-06-13 18:00:15.957 | INFO     | manager.bot:__V1_check_auth:461 - [ChatGPT-Web] - marklyons@sokaai.com 的 access_token 还有 5 天过期
2023-06-13 18:00:21.058 | ERROR    | manager.bot:login_openai:358 - 未知错误：
2023-06-13 18:00:21.059 | ERROR    | manager.bot:login_openai:359 -
Traceback (most recent call last):

  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\anyio\streams\tls.py", line 131, in _call_sslobject_method
    result = func(*args)
             │     └ (65536,)
             └ <bound method SSLObject.read of <ssl.SSLObject object at 0x000001916F895850>>

  File "ssl.py", line 921, in read

ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2546)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
                 │    │       │                 └ 65536
                 │    │       └ <function TLSStream.receive at 0x00000191487716C0>
                 │    └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x000001916F894D50>, standard_compatible=False, _...
                 └ <httpcore.backends.asyncio.AsyncIOStream object at 0x000001916F8957D0>
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\anyio\streams\tls.py", line 196, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
                 │    │                      │    │           │     └ 65536
                 │    │                      │    │           └ <function SSLObject.read at 0x0000019145855F80>
                 │    │                      │    └ <ssl.SSLObject object at 0x000001916F895850>
                 │    │                      └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x000001916F894D50>, standard_compatible=False, _...
                 │    └ <function TLSStream._call_sslobject_method at 0x00000191487714E0>
                 └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x000001916F894D50>, standard_compatible=False, _...
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\anyio\streams\tls.py", line 138, in _call_sslobject_method
    data = await self.transport_stream.receive()
                 │    │                └ <function SocketStream.receive at 0x000001916F8825C0>
                 │    └ <anyio._backends._asyncio.SocketStream object at 0x000001916F894D50>
                 └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x000001916F894D50>, standard_compatible=False, _...
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 1203, in receive
    await self._protocol.read_event.wait()
          │    │         │          └ <function Event.wait at 0x000001914707E840>
          │    │         └ <asyncio.locks.Event object at 0x000001916F84FCD0 [set]>
          │    └ <anyio._backends._asyncio.StreamProtocol object at 0x00000191470C1990>
          └ <anyio._backends._asyncio.SocketStream object at 0x000001916F894D50>

  File "asyncio\locks.py", line 213, in wait
    true will not block at all.

asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 32, in read
    with anyio.fail_after(timeout):
         │     │          └ 5.0
         │     └ <function fail_after at 0x0000019148720E00>
         └ <module 'anyio' from 'C:\\Users\\Zhuuu_F-Will\\Desktop\\机器人\\python3.11\\Lib\\site-packages\\anyio\\__init__.py'>
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\anyio\_core\_tasks.py", line 119, in __exit__
    raise TimeoutError

TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
                 │    │     │                    └ <Request [b'GET']>
                 │    │     └ <function AsyncConnectionPool.handle_async_request at 0x0000019148934E00>
                 │    └ <httpcore.AsyncHTTPProxy object at 0x000001916F858990>
                 └ <httpx.AsyncHTTPTransport object at 0x000001916F858F50>
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpcore\_async\connection_pool.py", line 261, in handle_async_request
    raise exc
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpcore\_async\connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
                     │          │                    └ <Request [b'GET']>
                     │          └ <function AsyncTunnelHTTPConnection.handle_async_request at 0x0000019148935E40>
                     └ <AsyncTunnelHTTPConnection ['https://bypass.churchless.tech:443', HTTP/1.1, CLOSED, Request Count: 1]>
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpcore\_async\http_proxy.py", line 326, in handle_async_request
    return await self._connection.handle_async_request(request)
                 │    │           │                    └ <Request [b'GET']>
                 │    │           └ <function AsyncHTTP11Connection.handle_async_request at 0x00000191489172E0>
                 │    └ <AsyncHTTP11Connection ['https://bypass.churchless.tech:443', CLOSED, Request Count: 1]>
                 └ <AsyncTunnelHTTPConnection ['https://bypass.churchless.tech:443', HTTP/1.1, CLOSED, Request Count: 1]>
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpcore\_async\http11.py", line 120, in handle_async_request
    raise exc
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpcore\_async\http11.py", line 99, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
              │    │                           └ {'request': <Request [b'GET']>}
              │    └ <function AsyncHTTP11Connection._receive_response_headers at 0x0000019148917560>
              └ <AsyncHTTP11Connection ['https://bypass.churchless.tech:443', CLOSED, Request Count: 1]>
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpcore\_async\http11.py", line 163, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
                  │    │                      └ 5.0
                  │    └ <function AsyncHTTP11Connection._receive_event at 0x00000191489176A0>
                  └ <AsyncHTTP11Connection ['https://bypass.churchless.tech:443', CLOSED, Request Count: 1]>
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpcore\_async\http11.py", line 199, in _receive_event
    data = await self._network_stream.read(
                 │    │               └ <function AsyncIOStream.read at 0x000001916F89DEE0>
                 │    └ <httpcore.backends.asyncio.AsyncIOStream object at 0x000001916F8957D0>
                 └ <AsyncHTTP11Connection ['https://bypass.churchless.tech:443', CLOSED, Request Count: 1]>
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 31, in read
    with map_exceptions(exc_map):
         │              └ {<class 'TimeoutError'>: <class 'httpcore.ReadTimeout'>, <class 'anyio.BrokenResourceError'>: <class 'httpcore.ReadError'>, <...
         └ <function map_exceptions at 0x00000191486D0EA0>

  File "contextlib.py", line 155, in __exit__

  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
          └ <class 'httpcore.ReadTimeout'>

httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\chatgpt\bot.py", line 17, in <module>
    loop.run_until_complete(botManager.login())
    │    │                  │          └ <function BotManager.login at 0x000001916E67A5C0>
    │    │                  └ <manager.bot.BotManager object at 0x000001916E6BDF10>
    │    └ <function BaseEventLoop.run_until_complete at 0x0000019147092840>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001916F873040>()>

  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\chatgpt\manager\bot.py", line 148, in login
    await self.login_openai()
          │    └ <function BotManager.login_openai at 0x000001916E6A14E0>
          └ <manager.bot.BotManager object at 0x000001916E6BDF10>

> File "C:\Users\Zhuuu_F-Will\Desktop\机器人\chatgpt\manager\bot.py", line 335, in login_openai
    bot = await self.__login_V1(account)
                │               └ OpenAIAccessTokenAuth(mode='browserless', proxy='http://127.0.0.1:7890', driver_exec_path=None, browser_exec_path=None, conve...
                └ <manager.bot.BotManager object at 0x000001916E6BDF10>

  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\chatgpt\manager\bot.py", line 472, in __login_V1
    if await __V1_check_auth():

  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\chatgpt\manager\bot.py", line 462, in __V1_check_auth
    await bot.get_conversations(0, 1)
          │   └ <function AsyncChatbot.get_conversations at 0x000001916E66F600>
          └ <revChatGPT.V1.AsyncChatbot object at 0x000001916F83E750>

  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\revChatGPT\V1.py", line 1194, in get_conversations
    response = await self.session.get(url)
                     │    │       │   └ 'https://bypass.churchless.tech/api/conversations?offset=0&limit=1'
                     │    │       └ <function AsyncClient.get at 0x00000191489476A0>
                     │    └ <httpx.AsyncClient object at 0x000001916F83F190>
                     └ <revChatGPT.V1.AsyncChatbot object at 0x000001916F83E750>
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
                 │    └ <function AsyncClient.request at 0x0000019148947240>
                 └ <httpx.AsyncClient object at 0x000001916F83F190>
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
                 │    │    │             │                      └ <httpx._client.UseClientDefault object at 0x000001914893F090>
                 │    │    │             └ <httpx._client.UseClientDefault object at 0x000001914893F090>
                 │    │    └ <Request('GET', 'https://bypass.churchless.tech/api/conversations?offset=0&limit=1')>
                 │    └ <function AsyncClient.send at 0x0000019148947420>
                 └ <httpx.AsyncClient object at 0x000001916F83F190>
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
                     │    └ <function AsyncClient._send_handling_auth at 0x00000191489474C0>
                     └ <httpx.AsyncClient object at 0x000001916F83F190>
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
                     │    └ <function AsyncClient._send_handling_redirects at 0x0000019148947560>
                     └ <httpx.AsyncClient object at 0x000001916F83F190>
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
                     │    │                    └ <Request('GET', 'https://bypass.churchless.tech/api/conversations?offset=0&limit=1')>
                     │    └ <function AsyncClient._send_single_request at 0x0000019148947600>
                     └ <httpx.AsyncClient object at 0x000001916F83F190>
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
                     │         │                    └ <Request('GET', 'https://bypass.churchless.tech/api/conversations?offset=0&limit=1')>
                     │         └ <function AsyncHTTPTransport.handle_async_request at 0x00000191489445E0>
                     └ <httpx.AsyncHTTPTransport object at 0x000001916F858F50>
  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
         └ <function map_httpcore_exceptions at 0x00000191486A72E0>

  File "contextlib.py", line 155, in __exit__

  File "C:\Users\Zhuuu_F-Will\Desktop\机器人\python3.11\Lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
          │          └ ''
          └ <class 'httpx.ReadTimeout'>

httpx.ReadTimeout
2023-06-13 18:00:21.102 | SUCCESS  | manager.bot:login_openai:362 - 成功登录 0/1 个 OpenAI 账号！
2023-06-13 18:00:21.102 | ERROR    | manager.bot:login:155 - 没有登录成功的账号，程序无法启动！
程序已停止运行。
Press any key to continue . . .

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by Zhuuufyuu** [comment]
第一次报错显示OpenAI:ping (code:404)
![报错](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/136446890/34c5c3c2-158a-46e5-a725-22bde82f68de)
后面几次报错就变成未知错误了
![3c0b45d2189d1a0a8b96156f257d820](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/136446890/14892df1-1314-404b-bed0-5ccc4630a160)
![7ee8cfc94de3dbf06f0929a00e8dd1f](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/136446890/28d7e81f-9f7a-4605-8fb0-3a014c2b024c)
![c48526b1f931288a14134c8194cef29](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/136446890/f7f2aa94-6080-43f7-a375-e5c05ff7032e)
修改access_token后报错又变成这样了
![e17e74a7c8c075476c847c61e2aeda4](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/136446890/b5c98d4c-9ea9-4b63-976a-af8acd343878)

**Comment by Zhuuufyuu** [comment]
> 网络问题，请重试

这几次报错都是网络问题嘛，我看了其他的issue，有没有可能是切入点的问题呢。感谢回答

**Comment by Mr-richrich** [comment]
网络问题吗？我人在海外也遇到了相同的情况，亚马逊的服务器

**Comment by Mr-richrich** [comment]
网络问题吗？我人在海外也遇到了相同的情况，亚马逊的服务器

**Comment by Mr-richrich** [comment]
> 网络问题，请重试

网络问题吗？我人在海外也遇到了相同的情况，亚马逊的服务器
