### ISSUE TITLE
[BUG] openai token显示未知错误

### ISSUE THREAD

**Issue by FFoopp** [lss233/kirara-ai#997]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中，我还看了别人的问题，尝试browserless_endpoint = "https://bypass.churchless.tech/api/"也不行
- [ ] 我已看过其他 issue，他们不能解决我的问题 

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：window10
- Docker： ？
- 项目版本：最新版和旧版问题一样

**复现步骤**  
描述你是如何触发这个 BUG 的
我觉得可能开了其他VPN然后突然就用不了了token直接登录失败
**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过
Active code page: 65001
2023-06-28 08:48:33.476 | SUCCESS  | config:scan_presets:557 - 检查预设：聊天 <==> presets/issue402.txt [成功]
2023-06-28 08:48:33.479 | SUCCESS  | config:scan_presets:557 - 检查预设：猫娘 <==> presets/catgirl.txt [成功]
2023-06-28 08:48:33.480 | SUCCESS  | config:scan_presets:570 - 注册预设：bing <==> ./presets\assistant\bing.txt [成功]
2023-06-28 08:48:33.481 | SUCCESS  | config:scan_presets:570 - 注册预设：dan <==> ./presets\assistant\dan.txt [成功]
2023-06-28 08:48:33.482 | SUCCESS  | config:scan_presets:570 - 注册预设：debater <==> ./presets\assistant\debater.txt [ 成功]
2023-06-28 08:48:33.484 | SUCCESS  | config:scan_presets:570 - 注册预设：kp <==> ./presets\assistant\kp.txt [成功]
2023-06-28 08:48:33.486 | SUCCESS  | config:scan_presets:570 - 注册预设：lawyer <==> ./presets\assistant\lawyer.txt [成 功]
2023-06-28 08:48:33.487 | SUCCESS  | config:scan_presets:570 - 注册预设：long <==> ./presets\assistant\long.txt [成功]
2023-06-28 08:48:33.490 | SUCCESS  | config:scan_presets:570 - 注册预设：Lss233 <==> ./presets\assistant\Lss233.txt [成 功]
2023-06-28 08:48:33.491 | SUCCESS  | config:scan_presets:570 - 注册预设：novelist <==> ./presets\assistant\novelist.txt [成功]
2023-06-28 08:48:33.492 | SUCCESS  | config:scan_presets:570 - 注册预设：poet <==> ./presets\assistant\poet.txt [成功]
2023-06-28 08:48:33.493 | SUCCESS  | config:scan_presets:570 - 注册预设：shineisheji <==> ./presets\assistant\shineisheji.txt [成功]
2023-06-28 08:48:33.495 | SUCCESS  | config:scan_presets:570 - 注册预设：catgirl <==> ./presets\role-play\catgirl.txt [ 成功]
2023-06-28 08:48:33.496 | SUCCESS  | config:scan_presets:570 - 注册预设：cixiaogui <==> ./presets\role-play\cixiaogui.txt [成功]
2023-06-28 08:48:33.497 | SUCCESS  | config:scan_presets:570 - 注册预设：crazy <==> ./presets\role-play\crazy.txt [成功]
2023-06-28 08:48:33.498 | SUCCESS  | config:scan_presets:570 - 注册预设：debatestick <==> ./presets\role-play\debatestick.txt [成功]
2023-06-28 08:48:33.499 | SUCCESS  | config:scan_presets:570 - 注册预设：dingzhen <==> ./presets\role-play\dingzhen.txt [成功]
2023-06-28 08:48:33.500 | SUCCESS  | config:scan_presets:570 - 注册预设：DJ <==> ./presets\role-play\DJ.txt [成功]
2023-06-28 08:48:33.501 | SUCCESS  | config:scan_presets:570 - 注册预设：ERNIE <==> ./presets\role-play\ERNIE.txt [成功]
2023-06-28 08:48:33.502 | SUCCESS  | config:scan_presets:570 - 注册预设：gaoqiqiang <==> ./presets\role-play\gaoqiqiang.txt [成功]
2023-06-28 08:48:33.507 | SUCCESS  | config:scan_presets:570 - 注册预设：hanli <==> ./presets\role-play\hanli.txt [成功]
2023-06-28 08:48:33.509 | SUCCESS  | config:scan_presets:570 - 注册预设：huxijin <==> ./presets\role-play\huxijin.txt [ 成功]
2023-06-28 08:48:33.511 | SUCCESS  | config:scan_presets:570 - 注册预设：ikun <==> ./presets\role-play\ikun.txt [成功]
2023-06-28 08:48:33.512 | SUCCESS  | config:scan_presets:570 - 注册预设：jiabaili <==> ./presets\role-play\jiabaili.txt [成功]
2023-06-28 08:48:33.514 | SUCCESS  | config:scan_presets:570 - 注册预设：linruolan <==> ./presets\role-play\linruolan.txt [成功]
2023-06-28 08:48:33.515 | SUCCESS  | config:scan_presets:570 - 注册预设：MOSS <==> ./presets\role-play\MOSS.txt [成功]
2023-06-28 08:48:33.516 | SUCCESS  | config:scan_presets:570 - 注册预设：PG13succubus <==> ./presets\role-play\PG13succubus.txt [成功]
2023-06-28 08:48:33.518 | SUCCESS  | config:scan_presets:570 - 注册预设：powanlang <==> ./presets\role-play\powanlang.txt [成功]
2023-06-28 08:48:33.519 | SUCCESS  | config:scan_presets:570 - 注册预设：TsundereCatgirl <==> ./presets\role-play\TsundereCatgirl.txt [成功]
2023-06-28 08:48:33.525 | SUCCESS  | config:scan_presets:570 - 注册预设：welldone <==> ./presets\role-play\welldone.txt [成功]
2023-06-28 08:48:33.527 | SUCCESS  | config:scan_presets:570 - 注册预设：yutao <==> ./presets\role-play\yutao.txt [成功]
2023-06-28 08:48:33.528 | SUCCESS  | config:scan_presets:570 - 注册预设：zhangweiwei <==> ./presets\role-play\zhangweiwei.txt [成功]
2023-06-28 08:48:33.530 | ERROR    | config:scan_presets:567 - 注册预设：dan <==> ./presets\utils\dan.txt [失败：关键词 已存在]
2023-06-28 08:48:33.532 | ERROR    | config:scan_presets:567 - 注册预设：catgirl <==> ./presets\catgirl.txt [失败：关键 词已存在]
2023-06-28 08:48:33.533 | SUCCESS  | config:scan_presets:570 - 注册预设：catgirl_en <==> ./presets\catgirl_en.txt [成功]
2023-06-28 08:48:33.534 | SUCCESS  | config:scan_presets:570 - 注册预设：issue402 <==> ./presets\issue402.txt [成功]
2023-06-28 08:48:33.535 | SUCCESS  | config:scan_presets:570 - 注册预设：预设模板 <==> ./presets\预设模板.txt [成功]
2023-06-28 08:48:33.657 | INFO     | manager.bot:__check_proxy:393 - [代理测试] 正在检查代理配置：http://127.0.0.1:10808
2023-06-28 08:48:33.789 | SUCCESS  | manager.bot:__check_proxy:401 - [代理测试] 连接成功！
2023-06-28 08:48:33.791 | INFO     | manager.bot:login:130 - 当前的 browserless_endpoint 为：https://chatgpt-proxy.lss233.com/api/
2023-06-28 08:48:33.793 | INFO     | manager.bot:login:146 - 当前的 api_endpoint 为：https://api.openai.com/v1
2023-06-28 08:48:33.795 | INFO     | manager.bot:login_openai:329 - 正在登录第 1 个 OpenAI 账号
2023-06-28 08:48:33.796 | INFO     | manager.bot:__login_V1:419 - 模式：无浏览器登录
2023-06-28 08:48:33.797 | INFO     | manager.bot:__check_proxy:393 - [代理测试] 正在检查代理配置：http://127.0.0.1:15690
2023-06-28 08:48:34.164 | SUCCESS  | manager.bot:__check_proxy:401 - [代理测试] 连接成功！
2023-06-28 08:48:34.166 | INFO     | manager.bot:__login_V1:469 - 尝试使用 access_token 登录中...
2023-06-28 08:48:34.199 | INFO     | manager.bot:__V1_check_auth:461 - [ChatGPT-Web] - arlenearnold8087cc@web.de 的 access_token 还有 11 天过期
2023-06-28 08:48:34.475 | ERROR    | manager.bot:login_openai:358 - 未知错误：
2023-06-28 08:48:34.477 | ERROR    | manager.bot:login_openai:359 -
Traceback (most recent call last):

  File "D:\qqchat\3\python3.11\Lib\site-packages\anyio\streams\tls.py", line 131, in _call_sslobject_method
    result = func(*args)
             │     └ ()
             └ <bound method SSLObject.do_handshake of <ssl.SSLObject object at 0x0000014BEEFE4310>>

  File "ssl.py", line 979, in do_handshake

ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:992)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "D:\qqchat\3\python3.11\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "D:\qqchat\3\python3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 78, in start_tls
    raise exc
  File "D:\qqchat\3\python3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
                       │     │       │   │         └ <classmethod(<function TLSStream.wrap at 0x0000014BE7E4A340>)>
                       │     │       │   └ <class 'anyio.streams.tls.TLSStream'>
                       │     │       └ <module 'anyio.streams.tls' from 'D:\\qqchat\\3\\python3.11\\Lib\\site-packages\\anyio\\streams\\tls.py'>
                       │     └ <module 'anyio.streams' from 'D:\\qqchat\\3\\python3.11\\Lib\\site-packages\\anyio\\streams\\__init__.py'>
                       └ <module 'anyio' from 'D:\\qqchat\\3\\python3.11\\Lib\\site-packages\\anyio\\__init__.py'>
  File "D:\qqchat\3\python3.11\Lib\site-packages\anyio\streams\tls.py", line 123, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
          │       │                      │          └ <function SSLObject.do_handshake at 0x0000014BE4F4EB60>
          │       │                      └ <ssl.SSLObject object at 0x0000014BEEFE4310>
          │       └ <function TLSStream._call_sslobject_method at 0x0000014BE7E4A3E0>
          └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x0000014BEEF8EC10>, standard_compatible=False, _...
  File "D:\qqchat\3\python3.11\Lib\site-packages\anyio\streams\tls.py", line 152, in _call_sslobject_method
    raise BrokenResourceError from exc
          └ <class 'anyio.BrokenResourceError'>

anyio.BrokenResourceError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "D:\qqchat\3\python3.11\Lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\qqchat\3\python3.11\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
                 │    │     │                    └ <Request [b'GET']>
                 │    │     └ <function AsyncConnectionPool.handle_async_request at 0x0000014BE8019F80>
                 │    └ <httpcore.AsyncHTTPProxy object at 0x0000014BEEFA8810>
                 └ <httpx.AsyncHTTPTransport object at 0x0000014BEDDC2490>
  File "D:\qqchat\3\python3.11\Lib\site-packages\httpcore\_async\connection_pool.py", line 261, in handle_async_request
    raise exc
  File "D:\qqchat\3\python3.11\Lib\site-packages\httpcore\_async\connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
                     │          │                    └ <Request [b'GET']>
                     │          └ <function AsyncTunnelHTTPConnection.handle_async_request at 0x0000014BE801AFC0>
                     └ <AsyncTunnelHTTPConnection ['http://127.0.0.1:10808', HTTP/1.1, ACTIVE, Request Count: 1]>
  File "D:\qqchat\3\python3.11\Lib\site-packages\httpcore\_async\http_proxy.py", line 299, in handle_async_request
    stream = await stream.start_tls(**kwargs)
                   │      │           └ {'ssl_context': <ssl.SSLContext object at 0x0000014BEDED59A0>, 'server_hostname': 'chatgpt-proxy.lss233.com', 'timeout': 5.0}
                   │      └ <function AsyncIOStream.start_tls at 0x0000014BEEFDED40>
                   └ <httpcore.backends.asyncio.AsyncIOStream object at 0x0000014BEDDC1790>
  File "D:\qqchat\3\python3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 66, in start_tls
    with map_exceptions(exc_map):
         │              └ {<class 'TimeoutError'>: <class 'httpcore.ConnectTimeout'>, <class 'anyio.BrokenResourceError'>: <class 'httpcore.ConnectErro...
         └ <function map_exceptions at 0x0000014BE7DA5C60>

  File "contextlib.py", line 155, in __exit__

  File "D:\qqchat\3\python3.11\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
          └ <class 'httpcore.ConnectError'>

httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "D:\qqchat\3\chatgpt\bot.py", line 17, in <module>
    loop.run_until_complete(botManager.login())
    │    │                  │          └ <function BotManager.login at 0x0000014BEDD5EA20>
    │    │                  └ <manager.bot.BotManager object at 0x0000014BEDDA4610>
    │    └ <function BaseEventLoop.run_until_complete at 0x0000014BE6786E80>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x0000014BEEFB7F10>()>

  File "D:\qqchat\3\chatgpt\manager\bot.py", line 148, in login
    await self.login_openai()
          │    └ <function BotManager.login_openai at 0x0000014BEDD7DA80>
          └ <manager.bot.BotManager object at 0x0000014BEDDA4610>

> File "D:\qqchat\3\chatgpt\manager\bot.py", line 335, in login_openai
    bot = await self.__login_V1(account)
                │               └ OpenAIAccessTokenAuth(mode='browserless', proxy='http://127.0.0.1:15690', driver_exec_path=None, browser_exec_path=None, conv...
                └ <manager.bot.BotManager object at 0x0000014BEDDA4610>

  File "D:\qqchat\3\chatgpt\manager\bot.py", line 472, in __login_V1
    if await __V1_check_auth():

  File "D:\qqchat\3\chatgpt\manager\bot.py", line 462, in __V1_check_auth
    await bot.get_conversations(0, 1)
          │   └ <function AsyncChatbot.get_conversations at 0x0000014BEDD53BA0>
          └ <revChatGPT.V1.AsyncChatbot object at 0x0000014BE8683B50>

  File "D:\qqchat\3\python3.11\Lib\site-packages\revChatGPT\V1.py", line 1194, in get_conversations
    response = await self.session.get(url)
                     │    │       │   └ 'https://chatgpt-proxy.lss233.com/api/conversations?offset=0&limit=1'
                     │    │       └ <function AsyncClient.get at 0x0000014BE8028900>
                     │    └ <httpx.AsyncClient object at 0x0000014BEDDC1890>
                     └ <revChatGPT.V1.AsyncChatbot object at 0x0000014BE8683B50>
  File "D:\qqchat\3\python3.11\Lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
                 │    └ <function AsyncClient.request at 0x0000014BE80284A0>
                 └ <httpx.AsyncClient object at 0x0000014BEDDC1890>
  File "D:\qqchat\3\python3.11\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
                 │    │    │             │                      └ <httpx._client.UseClientDefault object at 0x0000014BE8024A50>
                 │    │    │             └ <httpx._client.UseClientDefault object at 0x0000014BE8024A50>
                 │    │    └ <Request('GET', 'https://chatgpt-proxy.lss233.com/api/conversations?offset=0&limit=1')>
                 │    └ <function AsyncClient.send at 0x0000014BE8028680>
                 └ <httpx.AsyncClient object at 0x0000014BEDDC1890>
  File "D:\qqchat\3\python3.11\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
                     │    └ <function AsyncClient._send_handling_auth at 0x0000014BE8028720>
                     └ <httpx.AsyncClient object at 0x0000014BEDDC1890>
  File "D:\qqchat\3\python3.11\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
                     │    └ <function AsyncClient._send_handling_redirects at 0x0000014BE80287C0>
                     └ <httpx.AsyncClient object at 0x0000014BEDDC1890>
  File "D:\qqchat\3\python3.11\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
                     │    │                    └ <Request('GET', 'https://chatgpt-proxy.lss233.com/api/conversations?offset=0&limit=1')>
                     │    └ <function AsyncClient._send_single_request at 0x0000014BE8028860>
                     └ <httpx.AsyncClient object at 0x0000014BEDDC1890>
  File "D:\qqchat\3\python3.11\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
                     │         │                    └ <Request('GET', 'https://chatgpt-proxy.lss233.com/api/conversations?offset=0&limit=1')>
                     │         └ <function AsyncHTTPTransport.handle_async_request at 0x0000014BE801D800>
                     └ <httpx.AsyncHTTPTransport object at 0x0000014BEDDC2490>
  File "D:\qqchat\3\python3.11\Lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
         └ <function map_httpcore_exceptions at 0x0000014BE7DA4040>

  File "contextlib.py", line 155, in __exit__

  File "D:\qqchat\3\python3.11\Lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
          │          └ ''
          └ <class 'httpx.ConnectError'>

httpx.ConnectError
2023-06-28 08:48:34.542 | SUCCESS  | manager.bot:login_openai:362 - 成功登录 0/1 个 OpenAI 账号！
2023-06-28 08:48:34.543 | ERROR    | manager.bot:login:155 - 没有登录成功的账号，程序无法启动！
程序已停止运行。
Press any key to continue . . .
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/95911838/0e46ed75-7e30-416d-b014-e563c5b535c0)

**其他内容**  
早上还能用，晚上就不行了

**Comment by lss233** [comment]
你这是网络不好吧

**Comment by FFoopp** [comment]
> 你是网络不好

不应该啊，所以今早我又登录一遍，网速看油管8k也是挺快的呀

**Comment by FFoopp** [comment]
好的谢谢，看来来这个clash不行了

**Comment by FFoopp** [comment]
好了，接了别人的接入点就好了

**Comment by woshizhanlang** [comment]
> 好了，接了别人的接入点就好了

大佬 能给鼠鼠个接入点吗

**Comment by woshizhanlang** [comment]
> 你这是网络不好吧

大佬 能给鼠鼠个接入点吗

**Comment by xiaocer** [comment]
所以这是什么问题呢？
