### ISSUE TITLE
（go-cqhttp版)[BUG]  鼠鼠我是纯小白 希望大佬给指点下

### ISSUE THREAD

**Issue by woshizhanlang** [lss233/kirara-ai#999]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况
鼠鼠我是纯小白 希望大佬给指点下
没配置python
 错误是
*_2023-06-28 22:44:12.786 | ERROR    | manager.bot:login_openai:358 - 未知错误：
2023-06-28 22:44:12.786 | ERROR    | manager.bot:login_openai:359 -_**
以下是全部代码
Active code page: 65001
2023-06-28 22:44:05.949 | SUCCESS  | config:scan_presets:557 - 检查预设：聊天 <==> presets/issue402.txt [成功]
2023-06-28 22:44:05.949 | SUCCESS  | config:scan_presets:557 - 检查预设：猫娘 <==> presets/catgirl.txt [成功]
2023-06-28 22:44:05.949 | SUCCESS  | config:scan_presets:570 - 注册预设：bing <==> ./presets\assistant\bing.txt [成功]
2023-06-28 22:44:05.949 | SUCCESS  | config:scan_presets:570 - 注册预设：dan <==> ./presets\assistant\dan.txt [成功]
2023-06-28 22:44:05.949 | SUCCESS  | config:scan_presets:570 - 注册预设：debater <==> ./presets\assistant\debater.txt [成功]
2023-06-28 22:44:05.949 | SUCCESS  | config:scan_presets:570 - 注册预设：kp <==> ./presets\assistant\kp.txt [成功]
2023-06-28 22:44:05.949 | SUCCESS  | config:scan_presets:570 - 注册预设：lawyer <==> ./presets\assistant\lawyer.txt [成功]
2023-06-28 22:44:05.949 | SUCCESS  | config:scan_presets:570 - 注册预设：long <==> ./presets\assistant\long.txt [成功]
2023-06-28 22:44:05.949 | SUCCESS  | config:scan_presets:570 - 注册预设：Lss233 <==> ./presets\assistant\Lss233.txt [成功]
2023-06-28 22:44:05.949 | SUCCESS  | config:scan_presets:570 - 注册预设：novelist <==> ./presets\assistant\novelist.txt [成功]
2023-06-28 22:44:05.949 | SUCCESS  | config:scan_presets:570 - 注册预设：poet <==> ./presets\assistant\poet.txt [成功]
2023-06-28 22:44:05.949 | SUCCESS  | config:scan_presets:570 - 注册预设：shineisheji <==> ./presets\assistant\shineisheji.txt [成功]
2023-06-28 22:44:05.949 | SUCCESS  | config:scan_presets:570 - 注册预设：catgirl <==> ./presets\role-play\catgirl.txt [成功]
2023-06-28 22:44:05.949 | SUCCESS  | config:scan_presets:570 - 注册预设：cixiaogui <==> ./presets\role-play\cixiaogui.txt [成功]
2023-06-28 22:44:05.949 | SUCCESS  | config:scan_presets:570 - 注册预设：crazy <==> ./presets\role-play\crazy.txt [成功]2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：debatestick <==> ./presets\role-play\debatestick.txt [成功]
2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：dingzhen <==> ./presets\role-play\dingzhen.txt [成功]
2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：DJ <==> ./presets\role-play\DJ.txt [成功]
2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：ERNIE <==> ./presets\role-play\ERNIE.txt [成功]2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：gaoqiqiang <==> ./presets\role-play\gaoqiqiang.txt [成功]
2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：hanli <==> ./presets\role-play\hanli.txt [成功]2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：huxijin <==> ./presets\role-play\huxijin.txt [成功]
2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：ikun <==> ./presets\role-play\ikun.txt [成功]
2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：jiabaili <==> ./presets\role-play\jiabaili.txt [成功]
2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：linruolan <==> ./presets\role-play\linruolan.txt [成功]
2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：MOSS <==> ./presets\role-play\MOSS.txt [成功]
2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：PG13succubus <==> ./presets\role-play\PG13succubus.txt [成功]
2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：powanlang <==> ./presets\role-play\powanlang.txt [成功]
2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：TsundereCatgirl <==> ./presets\role-play\TsundereCatgirl.txt [成功]
2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：welldone <==> ./presets\role-play\welldone.txt [成功]
2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：yutao <==> ./presets\role-play\yutao.txt [成功]2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：zhangweiwei <==> ./presets\role-play\zhangweiwei.txt [成功]
2023-06-28 22:44:05.964 | ERROR    | config:scan_presets:567 - 注册预设：dan <==> ./presets\utils\dan.txt [失败：关键词已存在]
2023-06-28 22:44:05.964 | ERROR    | config:scan_presets:567 - 注册预设：catgirl <==> ./presets\catgirl.txt [失败：关键词已存在]
2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：catgirl_en <==> ./presets\catgirl_en.txt [成功]2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：issue402 <==> ./presets\issue402.txt [成功]
2023-06-28 22:44:05.964 | SUCCESS  | config:scan_presets:570 - 注册预设：预设模板 <==> ./presets\预设模板.txt [成功]
2023-06-28 22:44:06.011 | INFO     | manager.bot:__check_proxy:393 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2023-06-28 22:44:07.038 | SUCCESS  | manager.bot:__check_proxy:401 - [代理测试] 连接成功！
2023-06-28 22:44:07.038 | INFO     | manager.bot:login:130 - 当前的 browserless_endpoint 为：https://chatgpt-proxy.lss233.com/api/
2023-06-28 22:44:07.038 | INFO     | manager.bot:login:146 - 当前的 api_endpoint 为：https://api.openai.com/v1
2023-06-28 22:44:07.038 | INFO     | manager.bot:login_openai:329 - 正在登录第 1 个 OpenAI 账号
2023-06-28 22:44:07.038 | INFO     | manager.bot:__login_V1:419 - 模式：无浏览器登录
2023-06-28 22:44:07.038 | INFO     | manager.bot:__check_proxy:393 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2023-06-28 22:44:07.330 | SUCCESS  | manager.bot:__check_proxy:401 - [代理测试] 连接成功！
2023-06-28 22:44:07.330 | INFO     | manager.bot:__login_V1:469 - 尝试使用 access_token 登录中...
2023-06-28 22:44:07.361 | INFO     | manager.bot:__V1_check_auth:461 - [ChatGPT-Web] - q1194635011@gmail.com 的 access_token 还有 13 天过期
**_2023-06-28 22:44:12.786 | ERROR    | manager.bot:login_openai:358 - 未知错误：
2023-06-28 22:44:12.786 | ERROR    | manager.bot:login_openai:359 -_**
Traceback (most recent call last):

  File "E:\QQGPT\python3.11\Lib\site-packages\anyio\streams\tls.py", line 131, in _call_sslobject_method
    result = func(*args)
             │     └ (65536,)
             └ <bound method SSLObject.read of <ssl.SSLObject object at 0x00000245B9CCC950>>

  File "ssl.py", line 921, in read

ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2546)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "E:\QQGPT\python3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
                 │    │       │                 └ 65536
                 │    │       └ <function TLSStream.receive at 0x0000024593DB53A0>
                 │    └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x00000245BAEA5050>, standard_compatible=False, _...
                 └ <httpcore.backends.asyncio.AsyncIOStream object at 0x00000245BAEDAED0>
  File "E:\QQGPT\python3.11\Lib\site-packages\anyio\streams\tls.py", line 196, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
                 │    │                      │    │           │     └ 65536
                 │    │                      │    │           └ <function SSLObject.read at 0x0000024590EA20C0>
                 │    │                      │    └ <ssl.SSLObject object at 0x00000245B9CCC950>
                 │    │                      └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x00000245BAEA5050>, standard_compatible=False, _...
                 │    └ <function TLSStream._call_sslobject_method at 0x0000024593DB51C0>
                 └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x00000245BAEA5050>, standard_compatible=False, _...
  File "E:\QQGPT\python3.11\Lib\site-packages\anyio\streams\tls.py", line 138, in _call_sslobject_method
    data = await self.transport_stream.receive()
                 │    │                └ <function SocketStream.receive at 0x00000245BAEE85E0>
                 │    └ <anyio._backends._asyncio.SocketStream object at 0x00000245BAEA5050>
                 └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x00000245BAEA5050>, standard_compatible=False, _...
  File "E:\QQGPT\python3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 1203, in receive
    await self._protocol.read_event.wait()
          │    │         │          └ <function Event.wait at 0x00000245926B6980>
          │    │         └ <asyncio.locks.Event object at 0x00000245BAEDA510 [set]>
          │    └ <anyio._backends._asyncio.StreamProtocol object at 0x00000245BAEA65D0>
          └ <anyio._backends._asyncio.SocketStream object at 0x00000245BAEA5050>

  File "asyncio\locks.py", line 213, in wait
    true will not block at all.

asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "E:\QQGPT\python3.11\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "E:\QQGPT\python3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 32, in read
    with anyio.fail_after(timeout):
         │     │          └ 5.0
         │     └ <function fail_after at 0x0000024593D54AE0>
         └ <module 'anyio' from 'E:\\QQGPT\\python3.11\\Lib\\site-packages\\anyio\\__init__.py'>
  File "E:\QQGPT\python3.11\Lib\site-packages\anyio\_core\_tasks.py", line 119, in __exit__
    raise TimeoutError

TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "E:\QQGPT\python3.11\Lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "E:\QQGPT\python3.11\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
                 │    │     │                    └ <Request [b'GET']>
                 │    │     └ <function AsyncConnectionPool.handle_async_request at 0x0000024593F74CC0>
                 │    └ <httpcore.AsyncHTTPProxy object at 0x00000245BAEA6650>
                 └ <httpx.AsyncHTTPTransport object at 0x00000245BAEA5ED0>
  File "E:\QQGPT\python3.11\Lib\site-packages\httpcore\_async\connection_pool.py", line 261, in handle_async_request
    raise exc
  File "E:\QQGPT\python3.11\Lib\site-packages\httpcore\_async\connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
                     │          │                    └ <Request [b'GET']>
                     │          └ <function AsyncTunnelHTTPConnection.handle_async_request at 0x0000024593F75D00>
                     └ <AsyncTunnelHTTPConnection ['https://chatgpt-proxy.lss233.com:443', HTTP/1.1, CLOSED, Request Count: 1]>
  File "E:\QQGPT\python3.11\Lib\site-packages\httpcore\_async\http_proxy.py", line 326, in handle_async_request
    return await self._connection.handle_async_request(request)
                 │    │           │                    └ <Request [b'GET']>
                 │    │           └ <function AsyncHTTP11Connection.handle_async_request at 0x0000024593F5F060>
                 │    └ <AsyncHTTP11Connection ['https://chatgpt-proxy.lss233.com:443', CLOSED, Request Count: 1]>
                 └ <AsyncTunnelHTTPConnection ['https://chatgpt-proxy.lss233.com:443', HTTP/1.1, CLOSED, Request Count: 1]>
  File "E:\QQGPT\python3.11\Lib\site-packages\httpcore\_async\http11.py", line 120, in handle_async_request
    raise exc
  File "E:\QQGPT\python3.11\Lib\site-packages\httpcore\_async\http11.py", line 99, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
              │    │                           └ {'request': <Request [b'GET']>}
              │    └ <function AsyncHTTP11Connection._receive_response_headers at 0x0000024593F5F2E0>
              └ <AsyncHTTP11Connection ['https://chatgpt-proxy.lss233.com:443', CLOSED, Request Count: 1]>
  File "E:\QQGPT\python3.11\Lib\site-packages\httpcore\_async\http11.py", line 163, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
                  │    │                      └ 5.0
                  │    └ <function AsyncHTTP11Connection._receive_event at 0x0000024593F5F420>
                  └ <AsyncHTTP11Connection ['https://chatgpt-proxy.lss233.com:443', CLOSED, Request Count: 1]>
  File "E:\QQGPT\python3.11\Lib\site-packages\httpcore\_async\http11.py", line 199, in _receive_event
    data = await self._network_stream.read(
                 │    │               └ <function AsyncIOStream.read at 0x00000245BAEEBEC0>
                 │    └ <httpcore.backends.asyncio.AsyncIOStream object at 0x00000245BAEDAED0>
                 └ <AsyncHTTP11Connection ['https://chatgpt-proxy.lss233.com:443', CLOSED, Request Count: 1]>
  File "E:\QQGPT\python3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 31, in read
    with map_exceptions(exc_map):
         │              └ {<class 'TimeoutError'>: <class 'httpcore.ReadTimeout'>, <class 'anyio.BrokenResourceError'>: <class 'httpcore.ReadError'>, <...
         └ <function map_exceptions at 0x0000024593D10B80>

  File "contextlib.py", line 155, in __exit__

  File "E:\QQGPT\python3.11\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
          └ <class 'httpcore.ReadTimeout'>

httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "E:\QQGPT\chatgpt\bot.py", line 17, in <module>
    loop.run_until_complete(botManager.login())
    │    │                  │          └ <function BotManager.login at 0x00000245B9C7C2C0>
    │    │                  └ <manager.bot.BotManager object at 0x00000245B9CAB7D0>
    │    └ <function BaseEventLoop.run_until_complete at 0x00000245926D2980>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x00000245BAEBBF70>()>

  File "E:\QQGPT\chatgpt\manager\bot.py", line 148, in login
    await self.login_openai()
          │    └ <function BotManager.login_openai at 0x00000245B9C7E8E0>
          └ <manager.bot.BotManager object at 0x00000245B9CAB7D0>

> File "E:\QQGPT\chatgpt\manager\bot.py", line 335, in login_openai
    bot = await self.__login_V1(account)
                │               └ OpenAIAccessTokenAuth(mode='browserless', proxy='http://127.0.0.1:7890', driver_exec_path=None, browser_exec_path=None, conve...
                └ <manager.bot.BotManager object at 0x00000245B9CAB7D0>

  File "E:\QQGPT\chatgpt\manager\bot.py", line 472, in __login_V1
    if await __V1_check_auth():

  File "E:\QQGPT\chatgpt\manager\bot.py", line 462, in __V1_check_auth
    await bot.get_conversations(0, 1)
          │   └ <function AsyncChatbot.get_conversations at 0x00000245B9C68A40>
          └ <revChatGPT.V1.AsyncChatbot object at 0x00000245B9CAB390>

  File "E:\QQGPT\python3.11\Lib\site-packages\revChatGPT\V1.py", line 1194, in get_conversations
    response = await self.session.get(url)
                     │    │       │   └ 'https://chatgpt-proxy.lss233.com/api/conversations?offset=0&limit=1'
                     │    │       └ <function AsyncClient.get at 0x0000024593F87560>
                     │    └ <httpx.AsyncClient object at 0x00000245B9CCE1D0>
                     └ <revChatGPT.V1.AsyncChatbot object at 0x00000245B9CAB390>
  File "E:\QQGPT\python3.11\Lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
                 │    └ <function AsyncClient.request at 0x0000024593F87100>
                 └ <httpx.AsyncClient object at 0x00000245B9CCE1D0>
  File "E:\QQGPT\python3.11\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
                 │    │    │             │                      └ <httpx._client.UseClientDefault object at 0x0000024593F80C10>
                 │    │    │             └ <httpx._client.UseClientDefault object at 0x0000024593F80C10>
                 │    │    └ <Request('GET', 'https://chatgpt-proxy.lss233.com/api/conversations?offset=0&limit=1')>
                 │    └ <function AsyncClient.send at 0x0000024593F872E0>
                 └ <httpx.AsyncClient object at 0x00000245B9CCE1D0>
  File "E:\QQGPT\python3.11\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
                     │    └ <function AsyncClient._send_handling_auth at 0x0000024593F87380>
                     └ <httpx.AsyncClient object at 0x00000245B9CCE1D0>
  File "E:\QQGPT\python3.11\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
                     │    └ <function AsyncClient._send_handling_redirects at 0x0000024593F87420>
                     └ <httpx.AsyncClient object at 0x00000245B9CCE1D0>
  File "E:\QQGPT\python3.11\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
                     │    │                    └ <Request('GET', 'https://chatgpt-proxy.lss233.com/api/conversations?offset=0&limit=1')>
                     │    └ <function AsyncClient._send_single_request at 0x0000024593F874C0>
                     └ <httpx.AsyncClient object at 0x00000245B9CCE1D0>
  File "E:\QQGPT\python3.11\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
                     │         │                    └ <Request('GET', 'https://chatgpt-proxy.lss233.com/api/conversations?offset=0&limit=1')>
                     │         └ <function AsyncHTTPTransport.handle_async_request at 0x0000024593F844A0>
                     └ <httpx.AsyncHTTPTransport object at 0x00000245BAEA5ED0>
  File "E:\QQGPT\python3.11\Lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
         └ <function map_httpcore_exceptions at 0x0000024593CE2F20>

  File "contextlib.py", line 155, in __exit__

  File "E:\QQGPT\python3.11\Lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
          │          └ ''
          └ <class 'httpx.ReadTimeout'>

httpx.ReadTimeout
2023-06-28 22:44:12.817 | SUCCESS  | manager.bot:login_openai:362 - 成功登录 0/1 个 OpenAI 账号！
2023-06-28 22:44:12.817 | ERROR    | manager.bot:login:155 - 没有登录成功的账号，程序无法启动！
程序已停止运行。
Press any key to continue . . .

**Comment by FFoopp** [comment]
它说网络延迟了，和我昨天发那个一样

**Comment by FFoopp** [comment]
你需要找一个别人分享的接入点进行链接

**Comment by woshizhanlang** [comment]
> 
哥 能加下你qq指导下鼠鼠吗 鼠鼠没看懂

**Comment by woshizhanlang** [comment]
哥 能加下你qq指导下鼠鼠吗 鼠鼠没看懂
&nbsp;我的QQ是1194635011




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月29日(星期四) 上午8:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lss233/chatgpt-mirai-qq-bot] （go-cqhttp版)[BUG]  鼠鼠我是纯小白 希望大佬给指点下 (Issue #999)





 
你需要找一个别人分享的接入点进行链接

**Comment by Nothingness-Void** [comment]
https://github.com/lss233/chatgpt-mirai-qq-bot/issues/981#issue-1771847686

**Comment by Reckl4ss** [comment]
代理问题吧 代理配置好了吗
